import type { EnrichedInsightSlug, InsightEntry } from '@/lib/enriched-insights'

type AdditionalInsightSlug = Extract<EnrichedInsightSlug,
  | 'website-portal-or-custom-app'
  | 'what-to-automate-first'
  | 'website-redesign-or-conversion-refresh'
  | 'build-buy-or-integrate-technology'
  | 'website-after-launch'
  | 'trade-show-leads-after-qr-scan'
  | 'workshop-consultant-or-fractional-leader'
  | 'practical-ai-use-cases'
>

export const ADDITIONAL_INSIGHTS: Record<AdditionalInsightSlug, InsightEntry> = {
  'website-portal-or-custom-app': {
    image: '/images/insights/library/website-portal-or-custom-app.webp',
    en: {
      category: 'Digital Products',
      imageAlt: 'A business owner and advisor compare a public website, client portal and workflow application.',
      plainAnswer: 'Choose a website to explain and attract, a portal to serve known users securely, and an application when people need to complete a repeatable workflow.',
      intro: ['These options can look similar on a proposal, but they solve different business problems. A marketing website helps people discover, understand and contact you. A client portal gives identified users secure access to information or services. A custom application supports tasks, rules, roles and data that generic pages cannot manage well.', 'The right decision begins with the outcome, not the feature list. Clarify who will use it, what they must accomplish, what information is sensitive and how the work happens today.'],
      exampleTitle: 'A booking request is not always an application',
      example: 'A clinic may need a clear website and a reliable booking connection, not custom software. If clients must later upload documents, view private plans and complete guided steps, a portal may become justified. Building only what the journey requires keeps cost and complexity under control.',
      signsTitle: 'Use these signals to classify the need',
      signs: ['Public information and lead generation point to a website.', 'Secure customer records and self service point to a portal.', 'Roles, rules and multi-step work point to an application.', 'A standard platform may be enough when the process is common.', 'Integration matters when information already lives elsewhere.', 'A phased release is safer when needs are still evolving.'],
      stepsTitle: 'Decide before you design',
      steps: [{ title: 'Name the outcome', body: 'Describe the customer, revenue or operational result in one sentence.' }, { title: 'Map the journey', body: 'List the users, decisions, information and exceptions involved from start to finish.' }, { title: 'Choose the smallest fit', body: 'Compare configuration, integration and custom development before committing to a build.' }],
      takeaway: 'The best solution is not the most sophisticated one. It is the simplest maintainable capability that creates the required value.',
      ctaTitle: 'Not sure whether you need a site, portal or application?',
      ctaText: 'ROALLA can clarify the journey, identify the smallest useful solution and turn it into a practical scope.',
      serviceHref: '/services/digital-products', serviceLabel: 'Explore Applications and Digital Products',
    },
    fr: {
      category: 'Produits numériques',
      imageAlt: 'Une propriétaire et un conseiller comparent un site public, un portail client et une application de travail.',
      plainAnswer: 'Choisissez un site pour expliquer et attirer, un portail pour servir des utilisateurs connus en sécurité et une application pour soutenir un processus répétable.',
      intro: ['Ces options peuvent sembler semblables dans une proposition, mais elles répondent à des besoins différents. Un site marketing aide les gens à vous découvrir et à communiquer avec vous. Un portail donne aux utilisateurs identifiés un accès sécurisé. Une application soutient des tâches, des règles, des rôles et des données qu’une page ordinaire gère mal.', 'La bonne décision commence par le résultat, pas par la liste de fonctions. Précisez qui utilisera la solution, ce que cette personne doit accomplir, quelles données sont sensibles et comment le travail se fait actuellement.'],
      exampleTitle: 'Une demande de rendez-vous ne justifie pas toujours une application',
      example: 'Une clinique peut avoir besoin d’un site clair relié à un bon outil de réservation. Si les clients doivent ensuite transmettre des documents, consulter un plan privé et suivre des étapes guidées, un portail peut devenir pertinent. Construire seulement ce que le parcours exige limite les coûts et la complexité.',
      signsTitle: 'Ces indices aident à classer le besoin',
      signs: ['Information publique et acquisition indiquent un site.', 'Dossiers privés et libre-service indiquent un portail.', 'Rôles, règles et étapes indiquent une application.', 'Une plateforme existante suffit parfois pour un processus courant.', 'Une intégration est utile lorsque les données existent déjà ailleurs.', 'Une livraison progressive réduit le risque lorsque le besoin évolue.'],
      stepsTitle: 'Décider avant de concevoir',
      steps: [{ title: 'Nommer le résultat', body: 'Décrivez en une phrase le résultat client, financier ou opérationnel attendu.' }, { title: 'Cartographier le parcours', body: 'Dressez la liste des utilisateurs, décisions, données et exceptions.' }, { title: 'Choisir la solution minimale', body: 'Comparez configuration, intégration et développement sur mesure avant de construire.' }],
      takeaway: 'La meilleure solution n’est pas la plus complexe. C’est la capacité maintenable la plus simple qui produit la valeur recherchée.',
      ctaTitle: 'Site, portail ou application?', ctaText: 'ROALLA peut clarifier le parcours, déterminer la plus petite solution utile et la transformer en portée de projet.',
      serviceHref: '/services/digital-products', serviceLabel: 'Explorer les applications et produits numériques',
    },
  },
  'what-to-automate-first': {
    image: '/images/insights/library/what-to-automate-first.webp',
    en: {
      category: 'Workflow Automation', imageAlt: 'A team maps repetitive work and separates automation from human judgment.',
      plainAnswer: 'Automate stable, repetitive work with clear rules. Keep people responsible for exceptions, judgment, relationships and consequential decisions.',
      intro: ['The best first automation is rarely the most impressive. It is usually a frequent, predictable handoff that wastes time, creates errors or delays a customer response.', 'Automation should remove avoidable effort without hiding responsibility. If the process changes every week or nobody owns the exceptions, software will simply make the confusion move faster.'],
      exampleTitle: 'Start with one dependable handoff', example: 'A service company copies website inquiries into a spreadsheet, alerts a manager and sends the same acknowledgement each time. Capturing the data, routing it and confirming receipt are strong automation candidates. Deciding whether the request is a good fit still belongs to a person.',
      signsTitle: 'A useful first automation has', signs: ['Enough volume to make saved time meaningful.', 'A stable trigger and a clear expected result.', 'Structured information that systems can read.', 'An owner for failures and unusual cases.', 'A manual fallback when a connection is unavailable.', 'A measure such as time saved, errors reduced or response speed.'],
      stepsTitle: 'Choose the first opportunity', steps: [{ title: 'Observe the work', body: 'Follow the real process and count copying, waiting, corrections and follow-ups.' }, { title: 'Separate rules from judgment', body: 'Automate predictable movement while keeping accountable decisions with people.' }, { title: 'Pilot and measure', body: 'Test one flow, monitor failures and confirm value before expanding.' }],
      takeaway: 'Good automation makes ownership clearer. It does not remove the people needed to handle context, care and exceptions.',
      ctaTitle: 'Which workflow is costing your team the most time?', ctaText: 'ROALLA can review one workflow, identify a safe starting point and design the controls needed to keep it dependable.',
      serviceHref: '/services/automation', serviceLabel: 'Explore Workflow Automation',
    },
    fr: {
      category: 'Automatisation des flux', imageAlt: 'Une équipe cartographie le travail répétitif et distingue automatisation et jugement humain.',
      plainAnswer: 'Automatisez le travail stable, répétitif et régi par des règles claires. Confiez aux personnes les exceptions, le jugement, les relations et les décisions importantes.',
      intro: ['La meilleure première automatisation est rarement la plus spectaculaire. Il s’agit souvent d’un transfert fréquent et prévisible qui gaspille du temps, crée des erreurs ou retarde une réponse au client.', 'L’automatisation doit retirer les efforts évitables sans masquer les responsabilités. Si le processus change chaque semaine ou si personne ne gère les exceptions, le logiciel accélérera simplement la confusion.'],
      exampleTitle: 'Commencer par un transfert fiable', example: 'Une entreprise copie les demandes Web dans un tableur, avise une gestionnaire et envoie toujours le même accusé de réception. Saisir les données, les acheminer et confirmer leur réception sont de bons candidats. Décider si la demande convient à l’entreprise demeure une responsabilité humaine.',
      signsTitle: 'Une bonne première automatisation possède', signs: ['Un volume suffisant pour produire un gain réel.', 'Un déclencheur stable et un résultat clair.', 'Des données structurées que les systèmes peuvent lire.', 'Une personne responsable des erreurs et exceptions.', 'Une solution manuelle lorsque la connexion échoue.', 'Une mesure comme le temps, les erreurs ou la vitesse de réponse.'],
      stepsTitle: 'Choisir la première occasion', steps: [{ title: 'Observer le travail', body: 'Suivez le vrai processus et comptez les copies, attentes, corrections et relances.' }, { title: 'Séparer règles et jugement', body: 'Automatisez les mouvements prévisibles et gardez les décisions responsables chez les personnes.' }, { title: 'Tester et mesurer', body: 'Validez un flux, surveillez les erreurs et confirmez la valeur avant de l’étendre.' }],
      takeaway: 'Une bonne automatisation clarifie les responsabilités. Elle ne retire pas les personnes nécessaires au contexte, au soin et aux exceptions.',
      ctaTitle: 'Quel flux coûte le plus de temps à votre équipe?', ctaText: 'ROALLA peut examiner un processus, choisir un point de départ sûr et concevoir les contrôles nécessaires.',
      serviceHref: '/services/automation', serviceLabel: 'Explorer l’automatisation des flux',
    },
  },
  'website-redesign-or-conversion-refresh': {
    image: '/images/insights/library/website-redesign-or-conversion-refresh.webp',
    en: {
      category: 'Website Design', imageAlt: 'A business owner and web strategist review an existing site and a focused improvement plan.',
      plainAnswer: 'Refresh the conversion path when the foundation still works. Redesign when structure, technology, brand and content all prevent meaningful improvement.',
      intro: ['A disappointing website does not automatically need to be replaced. Sometimes visitors simply cannot tell what the business offers, who it serves or what to do next. Those problems may be solved with stronger pages, clearer calls to action and better forms.', 'A rebuild becomes reasonable when mobile use is poor, routine updates are difficult, the design no longer represents the business or the platform blocks performance, accessibility and integration work.'],
      exampleTitle: 'Fix the decision path before replacing everything', example: 'A professional firm receives traffic but few inquiries. The platform is stable and fast, yet the service pages are vague and every button leads to a general contact form. A focused refresh can clarify the offer and create suitable inquiry paths without paying for a complete rebuild.',
      signsTitle: 'A redesign is more likely when', signs: ['The structure no longer matches the services.', 'Mobile visitors struggle with navigation or forms.', 'Important changes require fragile workarounds.', 'Performance or accessibility issues are structural.', 'The brand has changed substantially.', 'Several focused improvements have failed to remove the same barrier.'],
      stepsTitle: 'Choose based on evidence', steps: [{ title: 'Find the barrier', body: 'Review customer questions, analytics, forms, mobile use and page clarity.' }, { title: 'Test focused changes', body: 'Improve the highest value journey when the existing foundation can support it.' }, { title: 'Rebuild with a reason', body: 'Replace the site only when the expected gain justifies cost, migration and change.' }],
      takeaway: 'A redesign is a business decision, not a reaction to visual fatigue. Repair what works and replace what truly limits the customer journey.',
      ctaTitle: 'Does your site need a refresh or a rebuild?', ctaText: 'ROALLA can assess the current foundation and recommend the smallest change that can produce a credible improvement.',
      serviceHref: '/website-design', serviceLabel: 'Explore Business Website Design',
    },
    fr: {
      category: 'Conception de sites Web', imageAlt: 'Une propriétaire et une stratège Web examinent un site existant et un plan d’amélioration ciblé.',
      plainAnswer: 'Améliorez le parcours de conversion si la fondation fonctionne encore. Reconcevez le site lorsque structure, technologie, marque et contenu bloquent les progrès.',
      intro: ['Un site décevant ne doit pas automatiquement être remplacé. Les visiteurs comprennent parfois mal l’offre, le public visé ou la prochaine étape. Des pages plus claires, de meilleurs appels à l’action et des formulaires adaptés peuvent suffire.', 'Une refonte devient raisonnable lorsque l’expérience mobile est faible, les mises à jour sont difficiles, l’image ne représente plus l’entreprise ou la plateforme bloque performance, accessibilité et intégrations.'],
      exampleTitle: 'Corriger le parcours avant de tout remplacer', example: 'Un cabinet professionnel reçoit des visites, mais peu de demandes. La plateforme est stable et rapide, alors que les pages de services restent vagues et que chaque bouton mène au même formulaire. Une amélioration ciblée peut clarifier l’offre sans payer une refonte complète.',
      signsTitle: 'Une refonte est plus probable lorsque', signs: ['La structure ne correspond plus aux services.', 'La navigation ou les formulaires mobiles sont difficiles.', 'Chaque changement exige un contournement fragile.', 'Les problèmes de performance sont structurels.', 'La marque a beaucoup changé.', 'Plusieurs corrections ciblées n’ont pas retiré le même obstacle.'],
      stepsTitle: 'Décider selon les preuves', steps: [{ title: 'Trouver l’obstacle', body: 'Examinez questions clients, analytique, formulaires, mobile et clarté des pages.' }, { title: 'Tester une amélioration', body: 'Corrigez le parcours prioritaire si la fondation peut encore le soutenir.' }, { title: 'Refondre pour une raison', body: 'Remplacez le site lorsque le gain attendu justifie coût, migration et changement.' }],
      takeaway: 'Une refonte est une décision d’affaires, pas une réaction à la fatigue visuelle. Réparez ce qui fonctionne et remplacez ce qui limite vraiment le parcours.',
      ctaTitle: 'Votre site a-t-il besoin d’une amélioration ou d’une refonte?', ctaText: 'ROALLA peut évaluer la fondation et recommander le plus petit changement capable de produire un résultat crédible.',
      serviceHref: '/website-design', serviceLabel: 'Explorer la conception de sites Web',
    },
  },
  'build-buy-or-integrate-technology': {
    image: '/images/insights/library/build-buy-or-integrate-technology.webp',
    en: {
      category: 'Technology Advisory', imageAlt: 'A leader and independent advisor compare technology solution options and integration plans.',
      plainAnswer: 'Buy when a proven product fits the need, configure when differences are modest, integrate when useful systems must cooperate, and build only where the requirement creates distinct value.',
      intro: ['Technology decisions become expensive when teams begin with a favourite product or a requested feature. The useful starting point is a clear set of business, user, security, integration and cost requirements.', 'No option is free of tradeoffs. Buying can speed delivery but introduce licence limits. Building provides control but creates long-term ownership. Integration preserves useful tools but adds dependencies that must be monitored.'],
      exampleTitle: 'The cheapest licence may not be the lowest cost', example: 'A growing company chooses an inexpensive platform, then discovers that approvals, reporting and customer records require manual work. A requirements review might reveal that a better configured product plus one integration costs less than years of workarounds.',
      signsTitle: 'A sound comparison considers', signs: ['The outcome and essential requirements.', 'Implementation and migration effort.', 'Security, privacy and access controls.', 'Integration and data portability.', 'Support, ownership and exit options.', 'Total cost over several years, not only the initial price.'],
      stepsTitle: 'Make the choice in the right order', steps: [{ title: 'Define requirements', body: 'Separate essential outcomes from preferences and vendor terminology.' }, { title: 'Compare real options', body: 'Score qualified choices against the same operational, technical and commercial criteria.' }, { title: 'Plan adoption', body: 'Include migration, training, ownership, support and measures before signing.' }],
      takeaway: 'A technology recommendation is useful only when it can be traced back to your requirements and understood beyond the sales presentation.',
      ctaTitle: 'Need an impartial way to compare your options?', ctaText: 'ROALLA can define requirements, compare qualified solutions and prepare a practical implementation plan with commercial relationships disclosed.',
      serviceHref: '/programs/technology-advisory', serviceLabel: 'Explore Technology Advisory',
    },
    fr: {
      category: 'Conseil technologique', imageAlt: 'Un dirigeant et une conseillère indépendante comparent des solutions technologiques et leurs intégrations.',
      plainAnswer: 'Achetez lorsqu’un produit éprouvé répond au besoin, configurez si les écarts sont modestes, intégrez lorsque les bons systèmes doivent coopérer et construisez seulement ce qui crée une valeur distincte.',
      intro: ['Les décisions technologiques deviennent coûteuses lorsque l’équipe commence par un produit favori ou une fonction demandée. Le bon point de départ est un ensemble clair d’exigences d’affaires, d’usage, de sécurité, d’intégration et de coût.', 'Chaque option comporte des compromis. Acheter accélère parfois la livraison, mais impose des limites. Construire donne du contrôle, mais crée une responsabilité durable. Intégrer conserve les bons outils, mais ajoute des dépendances à surveiller.'],
      exampleTitle: 'La licence la moins chère ne donne pas toujours le coût le plus bas', example: 'Une entreprise choisit une plateforme économique, puis découvre que les approbations, rapports et dossiers clients exigent du travail manuel. Une analyse des exigences aurait pu montrer qu’un meilleur produit configuré avec une intégration coûte moins cher que des années de contournements.',
      signsTitle: 'Une comparaison sérieuse examine', signs: ['Le résultat et les exigences essentielles.', 'L’effort de mise en œuvre et de migration.', 'La sécurité, la confidentialité et les accès.', 'Les intégrations et la portabilité des données.', 'Le soutien, la propriété et les options de sortie.', 'Le coût total sur plusieurs années.'],
      stepsTitle: 'Choisir dans le bon ordre', steps: [{ title: 'Définir les exigences', body: 'Séparez résultats essentiels, préférences et vocabulaire des fournisseurs.' }, { title: 'Comparer les options', body: 'Évaluez les choix selon les mêmes critères opérationnels, techniques et commerciaux.' }, { title: 'Planifier l’adoption', body: 'Incluez migration, formation, responsabilités, soutien et mesures avant de signer.' }],
      takeaway: 'Une recommandation technologique est utile lorsqu’elle remonte clairement à vos exigences et reste compréhensible au-delà de la présentation commerciale.',
      ctaTitle: 'Besoin d’une comparaison impartiale?', ctaText: 'ROALLA peut définir les exigences, comparer des solutions qualifiées et préparer un plan de mise en œuvre avec divulgation des relations commerciales.',
      serviceHref: '/programs/technology-advisory', serviceLabel: 'Explorer le conseil technologique',
    },
  },
  'website-after-launch': {
    image: '/images/insights/library/website-after-launch.webp',
    en: {
      category: 'Managed Optimization', imageAlt: 'A business owner and digital specialist review website performance after launch.',
      plainAnswer: 'Launch creates a starting point. The site still needs monitoring, maintenance, measurement and focused improvement as customers, content and technology change.',
      intro: ['A website can launch successfully and lose value quietly. Forms stop delivering, links age, services change, software requires updates and customer behaviour reveals problems nobody could see in staging.', 'Ongoing optimization is not constant redesign. It is a disciplined rhythm of checking health, reviewing evidence and improving the highest value part of the journey.'],
      exampleTitle: 'The launch checklist cannot predict real use', example: 'A new site passes every test, but mobile visitors abandon a long inquiry form. Analytics and a few customer conversations reveal the friction. Shortening the form and improving the follow-up creates more value than adding another page.',
      signsTitle: 'A healthy post-launch practice includes', signs: ['Form and booking tests.', 'Security and dependency updates.', 'Performance and accessibility checks.', 'Analytics and conversion review.', 'Current services, team details and policies.', 'A prioritized improvement backlog with an owner.'],
      stepsTitle: 'Turn launch into a useful operating rhythm', steps: [{ title: 'Establish a baseline', body: 'Record technical health, traffic, key actions and known risks.' }, { title: 'Review regularly', body: 'Check failures, customer behaviour and business changes on an agreed schedule.' }, { title: 'Improve deliberately', body: 'Release focused changes, measure the effect and document what was learned.' }],
      takeaway: 'A website stays valuable when somebody is accountable for its health and improvement after the launch celebration ends.',
      ctaTitle: 'Who owns your website after launch?', ctaText: 'ROALLA can establish a baseline, maintain a transparent improvement backlog and deliver focused changes in a predictable cadence.',
      serviceHref: '/services/managed-optimization', serviceLabel: 'Explore Managed Optimization',
    },
    fr: {
      category: 'Optimisation gérée', imageAlt: 'Une propriétaire et un spécialiste examinent la performance du site après son lancement.',
      plainAnswer: 'Le lancement crée un point de départ. Le site exige encore suivi, entretien, mesure et amélioration lorsque clients, contenu et technologie changent.',
      intro: ['Un site peut réussir son lancement et perdre discrètement de la valeur. Les formulaires cessent de fonctionner, les liens vieillissent, les services changent, les logiciels exigent des mises à jour et le comportement réel révèle des problèmes invisibles en préparation.', 'L’optimisation continue n’est pas une refonte permanente. C’est un rythme discipliné qui vérifie la santé, examine les preuves et améliore la partie la plus utile du parcours.'],
      exampleTitle: 'La liste de lancement ne peut pas prédire l’usage réel', example: 'Un nouveau site réussit tous les tests, mais les visiteurs mobiles abandonnent un long formulaire. L’analytique et quelques conversations révèlent la friction. Raccourcir le formulaire et améliorer le suivi crée plus de valeur qu’ajouter une page.',
      signsTitle: 'Une bonne pratique après lancement comprend', signs: ['Des tests de formulaires et de réservation.', 'Des mises à jour de sécurité et dépendances.', 'Des contrôles de performance et accessibilité.', 'Une revue de l’analytique et des conversions.', 'Des services, équipes et politiques à jour.', 'Un carnet d’améliorations priorisé avec une personne responsable.'],
      stepsTitle: 'Créer un rythme utile', steps: [{ title: 'Établir une référence', body: 'Notez santé technique, trafic, actions importantes et risques connus.' }, { title: 'Réviser régulièrement', body: 'Examinez erreurs, comportement client et changements d’affaires selon un calendrier.' }, { title: 'Améliorer avec intention', body: 'Publiez des changements ciblés, mesurez leur effet et documentez les apprentissages.' }],
      takeaway: 'Un site reste utile lorsqu’une personne demeure responsable de sa santé et de son amélioration après le lancement.',
      ctaTitle: 'Qui est responsable de votre site après son lancement?', ctaText: 'ROALLA peut établir une référence, tenir un carnet transparent et livrer des améliorations ciblées selon une cadence prévisible.',
      serviceHref: '/services/managed-optimization', serviceLabel: 'Explorer l’optimisation gérée',
    },
  },
  'trade-show-leads-after-qr-scan': {
    image: '/images/insights/library/trade-show-leads-after-qr-scan.webp',
    en: {
      category: 'Digital Events', imageAlt: 'A trade show team connects a QR interaction with organized lead follow-up.',
      plainAnswer: 'A QR code creates an opening, not a relationship. Conversion depends on a useful mobile experience, meaningful context and timely follow-up.',
      intro: ['Event visitors are distracted, moving quickly and often using cellular service. Sending everyone to a general homepage forces them to reconstruct the conversation after they leave the booth.', 'A stronger event journey connects the scan to the topic, audience and next step. It also gives the team enough context to follow up like people who remember the conversation.'],
      exampleTitle: 'One booth can serve several intentions', example: 'A buyer wants a product comparison, a partner wants a collaboration brief and a journalist wants approved facts. Separate QR entry points can lead each person to the right concise resource while recording the context needed for appropriate follow-up.',
      signsTitle: 'A useful event journey provides', signs: ['Fast pages designed for phones and cellular connections.', 'A clear promise tied to the booth conversation.', 'Different paths for buyers, partners and media.', 'Forms that request only necessary information.', 'Consent and ownership for follow-up.', 'A post-event plan before the floor opens.'],
      stepsTitle: 'Design beyond the scan', steps: [{ title: 'Define the moments', body: 'List the booth conversations, audiences and next actions that matter.' }, { title: 'Build focused paths', body: 'Create fast pages, demos or tools that continue each specific conversation.' }, { title: 'Prepare follow-up', body: 'Assign owners, timing and messages before collecting the first lead.' }],
      takeaway: 'The QR code is only the bridge. The experience after the scan determines whether interest becomes a useful next conversation.',
      ctaTitle: 'Planning a booth, launch or business event?', ctaText: 'ROALLA can design the mobile journey, event pages and follow-up connections before the deadline becomes urgent.',
      serviceHref: '/services/digital-events', serviceLabel: 'Explore Digital Events',
    },
    fr: {
      category: 'Événements numériques', imageAlt: 'Une équipe de salon relie une interaction par code QR à un suivi organisé.',
      plainAnswer: 'Un code QR ouvre une porte, pas une relation. La conversion dépend d’une expérience mobile utile, d’un contexte significatif et d’un suivi rapide.',
      intro: ['Les visiteurs d’un événement sont distraits, se déplacent rapidement et utilisent souvent un réseau cellulaire. Envoyer tout le monde vers la page d’accueil les oblige à reconstruire la conversation après le kiosque.', 'Un meilleur parcours relie la lecture du code au sujet, au public et à la prochaine étape. Il donne aussi à l’équipe le contexte nécessaire pour faire un suivi qui respecte la conversation.'],
      exampleTitle: 'Un kiosque peut servir plusieurs intentions', example: 'Une acheteuse veut comparer le produit, un partenaire cherche un document de collaboration et une journaliste veut des faits approuvés. Des points d’entrée distincts peuvent mener chacun vers la bonne ressource tout en conservant le contexte du suivi.',
      signsTitle: 'Un parcours événementiel utile offre', signs: ['Des pages rapides sur téléphone et réseau cellulaire.', 'Une promesse liée à la conversation du kiosque.', 'Des chemins distincts pour acheteurs, partenaires et médias.', 'Des formulaires qui demandent seulement le nécessaire.', 'Un consentement et une responsabilité de suivi.', 'Un plan après événement prêt avant l’ouverture.'],
      stepsTitle: 'Concevoir au-delà du code', steps: [{ title: 'Définir les moments', body: 'Dressez la liste des conversations, publics et prochaines actions importantes.' }, { title: 'Créer des parcours ciblés', body: 'Construisez des pages ou outils rapides qui poursuivent chaque conversation.' }, { title: 'Préparer le suivi', body: 'Assignez responsabilités, délais et messages avant de recueillir le premier contact.' }],
      takeaway: 'Le code QR est seulement un pont. L’expérience suivante détermine si l’intérêt devient une conversation utile.',
      ctaTitle: 'Vous préparez un kiosque, un lancement ou un événement?', ctaText: 'ROALLA peut concevoir le parcours mobile, les pages et les connexions de suivi avant que l’échéance devienne urgente.',
      serviceHref: '/services/digital-events', serviceLabel: 'Explorer les événements numériques',
    },
  },
  'workshop-consultant-or-fractional-leader': {
    image: '/images/insights/library/workshop-consultant-or-fractional-leader.webp',
    en: {
      category: 'Business Enablement', imageAlt: 'A leader compares a facilitated workshop, advisory conversation and embedded fractional leadership.',
      plainAnswer: 'Choose a workshop to build shared understanding, consulting to solve a defined problem, and fractional leadership when the organization needs continuing senior ownership.',
      intro: ['Different forms of help create different kinds of progress. A workshop can align a group and produce a practical starting point. A consultant can investigate a problem and guide a defined change. A fractional leader joins the operating rhythm and remains accountable over time.', 'The wrong format creates predictable disappointment. A one-day session cannot replace months of leadership, while a long engagement may be unnecessary when the team only needs a facilitated decision.'],
      exampleTitle: 'The need determines the format', example: 'A team that cannot agree on priorities may begin with a decision workshop. If the problem involves unclear processes across departments, a focused advisory engagement may follow. If nobody has the capacity to lead implementation, fractional support can provide the missing ownership.',
      signsTitle: 'Match the format to the need', signs: ['Use a workshop for alignment, practice and shared language.', 'Use consulting for analysis and a defined improvement.', 'Use fractional leadership for continuing direction and accountability.', 'Consider team capacity, not only expertise.', 'Set a decision or outcome before choosing duration.', 'Clarify who owns implementation after the engagement.'],
      stepsTitle: 'Choose help that can produce the result', steps: [{ title: 'Describe the gap', body: 'Name whether the problem is understanding, expertise, capacity or ownership.' }, { title: 'Define the outcome', body: 'Specify what should be decided, changed or operating differently.' }, { title: 'Match the commitment', body: 'Choose the lightest format that can realistically deliver and sustain the result.' }],
      takeaway: 'The most valuable engagement is not always the longest one. It is the format that matches the real gap and leaves clear ownership behind.',
      ctaTitle: 'Which form of support fits your team?', ctaText: 'ROALLA can listen to the situation and recommend a workshop, focused advisory engagement or continuing leadership support.',
      serviceHref: '/programs/workshops', serviceLabel: 'Explore Team Workshops',
    },
    fr: {
      category: 'Accompagnement d’affaires', imageAlt: 'Une dirigeante compare atelier facilité, conseil ciblé et leadership fractionnel intégré.',
      plainAnswer: 'Choisissez un atelier pour bâtir une compréhension commune, le conseil pour résoudre un problème défini et le leadership fractionnel pour une responsabilité de direction continue.',
      intro: ['Les formes d’aide produisent des progrès différents. Un atelier peut aligner un groupe et créer un point de départ pratique. Une consultante peut analyser un problème et guider un changement défini. Une leader fractionnelle intègre le rythme de gestion et reste responsable dans le temps.', 'Le mauvais format crée une déception prévisible. Une journée ne remplace pas des mois de leadership, tandis qu’un long mandat est inutile si l’équipe a seulement besoin d’une décision facilitée.'],
      exampleTitle: 'Le besoin détermine le format', example: 'Une équipe qui ne s’entend pas sur les priorités peut commencer par un atelier de décision. Si le problème touche des processus entre services, un mandat ciblé peut suivre. Si personne ne peut diriger la mise en œuvre, un soutien fractionnel peut fournir la responsabilité manquante.',
      signsTitle: 'Associer le format au besoin', signs: ['Un atelier pour alignement, pratique et langage commun.', 'Le conseil pour analyse et amélioration définie.', 'Le leadership fractionnel pour direction et responsabilité continues.', 'La capacité de l’équipe compte autant que l’expertise.', 'Définissez le résultat avant la durée.', 'Précisez qui dirigera la mise en œuvre ensuite.'],
      stepsTitle: 'Choisir une aide capable de produire le résultat', steps: [{ title: 'Décrire l’écart', body: 'Précisez si le problème concerne compréhension, expertise, capacité ou responsabilité.' }, { title: 'Définir le résultat', body: 'Nommez ce qui doit être décidé, changé ou fonctionner autrement.' }, { title: 'Adapter l’engagement', body: 'Choisissez le format le plus léger capable de livrer et maintenir le résultat.' }],
      takeaway: 'Le mandat le plus utile n’est pas toujours le plus long. Il correspond au vrai besoin et laisse des responsabilités claires.',
      ctaTitle: 'Quelle forme de soutien convient à votre équipe?', ctaText: 'ROALLA peut écouter la situation et recommander un atelier, un mandat ciblé ou un soutien de leadership continu.',
      serviceHref: '/programs/workshops', serviceLabel: 'Explorer les ateliers d’équipe',
    },
  },
  'practical-ai-use-cases': {
    image: '/images/insights/library/practical-ai-use-cases.webp',
    en: {
      category: 'Practical AI', imageAlt: 'A small business team evaluates an AI-assisted workflow with a human review checkpoint.',
      plainAnswer: 'Start where work is repetitive, information is available and a person can verify the result. Avoid beginning with high consequence decisions or a tool looking for a problem.',
      intro: ['AI creates value when it improves a real workflow. Useful examples include extracting information from familiar documents, preparing a first draft, organizing requests or helping staff find approved knowledge.', 'The business still needs standards, secure data handling, human review and a way to measure quality. Saving a few minutes is not valuable if the team spends more time correcting unreliable output.'],
      exampleTitle: 'A modest use case can be the strongest one', example: 'A service team receives requests in several formats. AI can suggest a category and draft a summary, while an employee verifies both before routing the work. The team saves reading time without handing a consequential decision to the system.',
      signsTitle: 'A practical AI opportunity has', signs: ['A specific user and workflow.', 'Enough repeated work to justify change.', 'Representative information for testing.', 'A clear standard for acceptable output.', 'Human review proportional to the risk.', 'Measures for time, quality, adoption and failures.'],
      stepsTitle: 'Evaluate before scaling', steps: [{ title: 'Find the friction', body: 'Identify repetitive reading, drafting, classification or retrieval in a real process.' }, { title: 'Test safely', body: 'Use representative examples, protect sensitive information and compare results with a baseline.' }, { title: 'Design the control', body: 'Assign review, exception handling, monitoring and ownership before wider use.' }],
      takeaway: 'AI should earn its place in the workflow through measured usefulness. Novelty is not a business case.',
      ctaTitle: 'Where could AI help without weakening judgment?', ctaText: 'ROALLA can assess the workflow, define a responsible pilot and connect the technology to a useful operating result.',
      serviceHref: '/services/digital', serviceLabel: 'Explore AI and Intelligent Workflows',
    },
    fr: {
      category: 'IA pratique', imageAlt: 'Une petite équipe évalue un flux assisté par IA avec une étape de révision humaine.',
      plainAnswer: 'Commencez là où le travail est répétitif, les données sont disponibles et une personne peut vérifier le résultat. Évitez les décisions lourdes de conséquences et les outils sans problème défini.',
      intro: ['L’IA crée de la valeur lorsqu’elle améliore un vrai processus. Elle peut extraire de l’information de documents connus, préparer une première version, organiser des demandes ou aider le personnel à trouver des connaissances approuvées.', 'L’entreprise doit conserver des normes, une gestion sûre des données, une révision humaine et une mesure de qualité. Gagner quelques minutes ne sert à rien si l’équipe passe plus de temps à corriger des résultats faibles.'],
      exampleTitle: 'Un cas modeste peut être le plus solide', example: 'Une équipe reçoit des demandes sous plusieurs formats. L’IA peut suggérer une catégorie et rédiger un résumé, puis une employée vérifie les deux avant l’acheminement. Le temps de lecture diminue sans confier une décision importante au système.',
      signsTitle: 'Une occasion d’IA pratique possède', signs: ['Un utilisateur et un processus précis.', 'Assez de répétition pour justifier le changement.', 'Des exemples représentatifs pour les essais.', 'Une norme claire de résultat acceptable.', 'Une révision humaine adaptée au risque.', 'Des mesures de temps, qualité, adoption et erreurs.'],
      stepsTitle: 'Évaluer avant d’étendre', steps: [{ title: 'Trouver la friction', body: 'Repérez lecture, rédaction, classement ou recherche répétitive dans un vrai processus.' }, { title: 'Tester prudemment', body: 'Utilisez des exemples représentatifs, protégez les données et comparez avec une référence.' }, { title: 'Concevoir le contrôle', body: 'Assignez révision, exceptions, suivi et responsabilité avant un usage élargi.' }],
      takeaway: 'L’IA doit mériter sa place par une utilité mesurée. La nouveauté ne constitue pas une justification d’affaires.',
      ctaTitle: 'Où l’IA peut-elle aider sans affaiblir le jugement?', ctaText: 'ROALLA peut évaluer le processus, définir un projet pilote responsable et relier la technologie à un résultat utile.',
      serviceHref: '/services/digital', serviceLabel: 'Explorer l’IA et les flux intelligents',
    },
  },
}
