export const EXECUTIVE_GUIDE_CATEGORIES = [
  "all",
  "ai",
  "growth",
  "technology",
  "risk",
  "operations",
  "value",
] as const;

export type ExecutiveGuideCategory = Exclude<(typeof EXECUTIVE_GUIDE_CATEGORIES)[number], "all">;

export type ExecutiveGuide = {
  slug: string;
  number: string;
  category: ExecutiveGuideCategory;
  image: string;
  featured?: boolean;
  en: { title: string; summary: string; categoryLabel: string };
  fr: { title: string; summary: string; categoryLabel: string };
};

export const EXECUTIVE_GUIDES: readonly ExecutiveGuide[] = [
  {
    slug: "ai-readiness-governance",
    number: "EI—01",
    category: "ai",
    image: "/images/executive-insights/ai-manufacturing.png",
    featured: true,
    en: { title: "AI Readiness & Governance", summary: "Evaluate whether strategy, data, architecture, operating controls and leadership alignment are ready to support responsible AI at scale.", categoryLabel: "AI & automation" },
    fr: { title: "Préparation et gouvernance de l’IA", summary: "Évaluez si la stratégie, les données, l’architecture, les contrôles et l’alignement de la direction peuvent soutenir une IA responsable à grande échelle.", categoryLabel: "IA et automatisation" },
  },
  {
    slug: "acquisition-readiness-value-creation",
    number: "EI—02",
    category: "value",
    image: "/images/executive-insights/acquisition-readiness.png",
    en: { title: "Acquisition Readiness & Value Creation", summary: "Prepare the business, technology and operating evidence that increases buyer confidence and protects enterprise value.", categoryLabel: "Enterprise value" },
    fr: { title: "Préparation à l’acquisition et création de valeur", summary: "Préparez les preuves commerciales, technologiques et opérationnelles qui renforcent la confiance d’un acheteur et protègent la valeur.", categoryLabel: "Valeur d’entreprise" },
  },
  {
    slug: "saas-soc-2-readiness",
    number: "EI—03",
    category: "risk",
    image: "/images/executive-insights/saas-soc2-readiness.png",
    en: { title: "SaaS SOC 2 Readiness & Business Value", summary: "Turn compliance preparation into stronger controls, enterprise credibility and sales enablement.", categoryLabel: "Risk & resilience" },
    fr: { title: "Préparation SOC 2 pour SaaS et valeur d’affaires", summary: "Transformez la préparation à la conformité en contrôles plus solides, en crédibilité d’entreprise et en soutien aux ventes.", categoryLabel: "Risque et résilience" },
  },
  {
    slug: "digital-experience-modernization",
    number: "EI—04",
    category: "technology",
    image: "/images/executive-insights/digital-experience.png",
    en: { title: "Digital Experience Modernization", summary: "Improve adoption, accessibility and discoverability across UI/UX, SEO, AEO and agentic experiences.", categoryLabel: "Technology" },
    fr: { title: "Modernisation de l’expérience numérique", summary: "Améliorez l’adoption, l’accessibilité et la découvrabilité à travers l’UX, le référencement et les expériences agentiques.", categoryLabel: "Technologie" },
  },
  {
    slug: "smart-manufacturing-warehouse-modernization",
    number: "EI—05",
    category: "operations",
    image: "/images/executive-insights/smart-manufacturing.png",
    en: { title: "Smart Manufacturing & Warehouse Modernization", summary: "Prioritize automation and connected operations without creating fragmented technology or stranded investment.", categoryLabel: "Operations" },
    fr: { title: "Modernisation de la fabrication et des entrepôts", summary: "Priorisez l’automatisation et les opérations connectées sans fragmenter la technologie ni immobiliser les investissements.", categoryLabel: "Opérations" },
  },
  {
    slug: "sales-organization-growth-evolution",
    number: "EI—06",
    category: "growth",
    image: "/images/executive-insights/sales-growth.png",
    en: { title: "Sales Organization Growth & Evolution", summary: "Align roles, coverage, process, leadership and measurement to support the next stage of growth.", categoryLabel: "Growth & revenue" },
    fr: { title: "Croissance et évolution de l’organisation des ventes", summary: "Alignez les rôles, la couverture, les processus, le leadership et la mesure pour soutenir la prochaine étape de croissance.", categoryLabel: "Croissance et revenus" },
  },
  {
    slug: "cybersecurity-digital-resilience",
    number: "EI—07",
    category: "risk",
    image: "/images/executive-insights/cybersecurity.png",
    en: { title: "Cybersecurity & Digital Resilience", summary: "Connect cyber investment to operational continuity, customer trust and enterprise risk.", categoryLabel: "Risk & resilience" },
    fr: { title: "Cybersécurité et résilience numérique", summary: "Reliez les investissements cybernétiques à la continuité, à la confiance des clients et au risque d’entreprise.", categoryLabel: "Risque et résilience" },
  },
  {
    slug: "voice-unified-communications-modernization",
    number: "EI—08",
    category: "technology",
    image: "/images/executive-insights/voice-modernization.png",
    en: { title: "Voice & Unified Communications Modernization", summary: "Move from legacy voice and fragmented licensing to a modern, integrated communications strategy.", categoryLabel: "Technology" },
    fr: { title: "Modernisation de la voix et des communications unifiées", summary: "Passez de la téléphonie existante et des licences fragmentées à une stratégie de communication moderne et intégrée.", categoryLabel: "Technologie" },
  },
  {
    slug: "ai-manufacturing-warehouse-operations",
    number: "EI—09",
    category: "ai",
    image: "/images/executive-insights/ai-manufacturing.png",
    en: { title: "AI for Manufacturing & Warehouse Operations", summary: "Identify practical AI applications across planning, quality, maintenance, labour and throughput.", categoryLabel: "AI & automation" },
    fr: { title: "IA pour la fabrication et les opérations d’entrepôt", summary: "Repérez des applications concrètes de l’IA pour la planification, la qualité, l’entretien, la main-d’œuvre et le débit.", categoryLabel: "IA et automatisation" },
  },
  {
    slug: "technology-due-diligence",
    number: "EI—10",
    category: "value",
    image: "/images/executive-insights/strategic-value.png",
    en: { title: "Technology Due Diligence", summary: "Evaluate architecture, technical debt, security, IP, scalability and team dependency before a transaction.", categoryLabel: "Enterprise value" },
    fr: { title: "Diligence raisonnable technologique", summary: "Évaluez l’architecture, la dette technique, la sécurité, la propriété intellectuelle, l’évolutivité et la dépendance à l’équipe avant une transaction.", categoryLabel: "Valeur d’entreprise" },
  },
  {
    slug: "canadian-innovation-funding-qualification",
    number: "EI—11",
    category: "value",
    image: "/images/executive-insights/funding.png",
    en: { title: "Canadian Innovation Funding Qualification", summary: "Align qualified projects, evidence and spending plans to the Canadian innovation support landscape.", categoryLabel: "Funding" },
    fr: { title: "Qualification au financement canadien de l’innovation", summary: "Alignez les projets, les preuves et les dépenses admissibles sur l’écosystème canadien de soutien à l’innovation.", categoryLabel: "Financement" },
  },
  {
    slug: "revenue-operations-forecast-confidence",
    number: "EI—12",
    category: "growth",
    image: "/images/executive-insights/revops.png",
    en: { title: "Revenue Operations & Forecast Confidence", summary: "Create shared commercial truth across marketing, sales, customer success, data and forecasting.", categoryLabel: "Growth & revenue" },
    fr: { title: "Opérations de revenus et fiabilité des prévisions", summary: "Créez une vérité commerciale commune entre le marketing, les ventes, la réussite client, les données et les prévisions.", categoryLabel: "Croissance et revenus" },
  },
  {
    slug: "supply-chain-visibility-resilience",
    number: "EI—13",
    category: "operations",
    image: "/images/executive-insights/supply-chain.png",
    en: { title: "Supply Chain Visibility & Resilience", summary: "Improve decision velocity by connecting operational signals, ownership and response across the network.", categoryLabel: "Operations" },
    fr: { title: "Visibilité et résilience de la chaîne d’approvisionnement", summary: "Accélérez les décisions en reliant les signaux opérationnels, la responsabilité et la réponse dans l’ensemble du réseau.", categoryLabel: "Opérations" },
  },
  {
    slug: "ai-use-case-prioritization",
    number: "EI—14",
    category: "ai",
    image: "/images/executive-insights/ai-use-case-prioritization.png",
    en: { title: "AI Use Case Prioritization", summary: "Rank AI opportunities by strategic value, feasibility, data readiness, operating risk and measurable business outcomes.", categoryLabel: "AI & automation" },
    fr: { title: "Priorisation des cas d’usage de l’IA", summary: "Classez les possibilités d’IA selon la valeur stratégique, la faisabilité, la préparation des données, le risque opérationnel et les résultats mesurables.", categoryLabel: "IA et automatisation" },
  },
  {
    slug: "technology-transformation-readiness",
    number: "EI—15",
    category: "technology",
    image: "/images/executive-insights/technology-transformation.png",
    en: { title: "Technology Transformation Readiness", summary: "Connect business outcomes, legacy constraints, target architecture, delivery capacity and investment sequencing before transformation begins.", categoryLabel: "Technology" },
    fr: { title: "Préparation à la transformation technologique", summary: "Reliez les résultats d’affaires, les contraintes existantes, l’architecture cible, la capacité de livraison et le séquencement des investissements avant de transformer.", categoryLabel: "Technologie" },
  },
  {
    slug: "contact-centre-ai-transformation",
    number: "EI—16",
    category: "ai",
    image: "/images/executive-insights/contact-centre-ai.png",
    en: { title: "Contact Centre AI Transformation", summary: "Shape an AI portfolio across agent assist, interaction intelligence, self-service and voice automation while protecting service quality and trust.", categoryLabel: "AI & automation" },
    fr: { title: "Transformation du centre de contact par l’IA", summary: "Structurez un portefeuille d’IA couvrant l’assistance aux agents, l’intelligence des interactions, le libre-service et l’automatisation vocale tout en protégeant la qualité et la confiance.", categoryLabel: "IA et automatisation" },
  },
  {
    slug: "warehouse-automation-robotics-investment",
    number: "EI—17",
    category: "operations",
    image: "/images/executive-insights/warehouse-automation.png",
    en: { title: "Warehouse Automation & Robotics Investment", summary: "Assess demand, process stability, facility fit, integration, safety and economics before committing to warehouse automation.", categoryLabel: "Operations" },
    fr: { title: "Investissement en automatisation et robotique d’entrepôt", summary: "Évaluez la demande, la stabilité des processus, l’adéquation des installations, l’intégration, la sécurité et l’économie avant d’investir.", categoryLabel: "Opérations" },
  },
  {
    slug: "operational-technology-cybersecurity-resilience",
    number: "EI—18",
    category: "risk",
    image: "/images/executive-insights/ot-cybersecurity.png",
    en: { title: "Operational Technology Cybersecurity & Resilience", summary: "Protect connected facilities by aligning asset visibility, segmentation, access, monitoring, recovery and operational ownership.", categoryLabel: "Risk & resilience" },
    fr: { title: "Cybersécurité et résilience des technologies opérationnelles", summary: "Protégez les installations connectées en alignant la visibilité des actifs, la segmentation, les accès, la surveillance, la reprise et les responsabilités.", categoryLabel: "Risque et résilience" },
  },
  {
    slug: "erp-mes-wms-integration-readiness",
    number: "EI—19",
    category: "operations",
    image: "/images/executive-insights/erp-mes-wms.png",
    en: { title: "ERP, MES & WMS Integration Readiness", summary: "Clarify system roles, data ownership, process handoffs and integration controls before connecting core operational platforms.", categoryLabel: "Operations" },
    fr: { title: "Préparation à l’intégration ERP, MES et WMS", summary: "Clarifiez les rôles des systèmes, la propriété des données, les transferts de processus et les contrôles avant de connecter les plateformes opérationnelles.", categoryLabel: "Opérations" },
  },
  {
    slug: "industrial-technology-vendor-selection",
    number: "EI—20",
    category: "technology",
    image: "/images/executive-insights/vendor-selection.png",
    en: { title: "Industrial Technology Vendor Selection & Business Case", summary: "Build an evidence-led selection process that compares operating fit, integration, lifecycle cost, risk and measurable value.", categoryLabel: "Technology" },
    fr: { title: "Sélection de fournisseurs technologiques industriels et analyse de rentabilité", summary: "Créez un processus fondé sur les preuves qui compare l’adéquation opérationnelle, l’intégration, le coût du cycle de vie, le risque et la valeur.", categoryLabel: "Technologie" },
  },
  {
    slug: "energy-productivity-facility-modernization",
    number: "EI—21",
    category: "operations",
    image: "/images/executive-insights/energy-productivity.png",
    en: { title: "Energy Productivity & Facility Modernization", summary: "Prioritize facility and energy investments using credible baselines, operational constraints, resilience needs and verified economics.", categoryLabel: "Operations" },
    fr: { title: "Productivité énergétique et modernisation des installations", summary: "Priorisez les investissements dans les installations et l’énergie selon des références crédibles, les contraintes opérationnelles, la résilience et l’économie vérifiée.", categoryLabel: "Opérations" },
  },
  {
    slug: "go-to-market-strategy-readiness",
    number: "EI—22",
    category: "growth",
    image: "/images/executive-insights/go-to-market.png",
    en: { title: "Go-to-Market Strategy & Readiness", summary: "Select priority markets, sharpen positioning and align channels, capacity, economics and evidence before scaling commercial investment.", categoryLabel: "Growth & revenue" },
    fr: { title: "Stratégie de mise en marché et préparation", summary: "Sélectionnez les marchés prioritaires, précisez le positionnement et alignez les canaux, la capacité, l’économie et les preuves avant d’accélérer.", categoryLabel: "Croissance et revenus" },
  },
  {
    slug: "customer-success-revenue-retention",
    number: "EI—23",
    category: "growth",
    image: "/images/executive-insights/customer-success.png",
    en: { title: "Customer Success & Revenue Retention", summary: "Design customer journeys, ownership, health signals and intervention plays that protect adoption, retention and expansion.", categoryLabel: "Growth & revenue" },
    fr: { title: "Réussite client et rétention des revenus", summary: "Concevez les parcours, les responsabilités, les signaux de santé et les interventions qui protègent l’adoption, la rétention et l’expansion.", categoryLabel: "Croissance et revenus" },
  },
  {
    slug: "pricing-packaging-optimization",
    number: "EI—24",
    category: "growth",
    image: "/images/executive-insights/pricing-packaging.png",
    en: { title: "Pricing & Packaging Optimization", summary: "Align customer value, offer architecture, price metrics, discount discipline and commercial evidence to improve profitable growth.", categoryLabel: "Growth & revenue" },
    fr: { title: "Optimisation de la tarification et des offres", summary: "Alignez la valeur client, l’architecture des offres, les mesures de prix, la discipline des rabais et les preuves commerciales pour une croissance rentable.", categoryLabel: "Croissance et revenus" },
  },
  {
    slug: "marketing-revenue-alignment",
    number: "EI—25",
    category: "growth",
    image: "/images/executive-insights/marketing-revenue.png",
    en: { title: "Marketing-to-Revenue Alignment", summary: "Create shared definitions, operating rhythms, data and accountability across marketing, sales and customer success.", categoryLabel: "Growth & revenue" },
    fr: { title: "Alignement du marketing aux revenus", summary: "Créez des définitions, des rythmes opérationnels, des données et une responsabilité partagés entre le marketing, les ventes et la réussite client.", categoryLabel: "Croissance et revenus" },
  },
  {
    slug: "enterprise-sales-transformation",
    number: "EI—26",
    category: "growth",
    image: "/images/executive-insights/enterprise-sales.png",
    en: { title: "Enterprise Sales Transformation", summary: "Evolve segmentation, coverage, opportunity discipline, enablement and leadership systems for complex enterprise growth.", categoryLabel: "Growth & revenue" },
    fr: { title: "Transformation des ventes aux entreprises", summary: "Faites évoluer la segmentation, la couverture, la discipline des occasions, l’habilitation et le leadership pour soutenir la croissance complexe.", categoryLabel: "Croissance et revenus" },
  },
  {
    slug: "canadian-staff-augmentation-outlook-2027",
    number: "EI—27",
    category: "operations",
    image: "/images/executive-insights/staff-augmentation-2027.png",
    en: { title: "Canadian Staff Augmentation Outlook 2027", summary: "Use a parallel path to protect delivery capacity while controlling cost, applying technology and building stronger internal capability through trade uncertainty.", categoryLabel: "Workforce & productivity" },
    fr: { title: "Perspectives canadiennes 2027 sur l’augmentation des effectifs", summary: "Adoptez une approche parallèle pour protéger la capacité de livraison, maîtriser les coûts, appliquer la technologie et renforcer les capacités internes malgré l’incertitude commerciale.", categoryLabel: "Main-d’œuvre et productivité" },
  },
] as const;

export function findExecutiveGuide(slug: string) {
  return EXECUTIVE_GUIDES.find((guide) => guide.slug === slug);
}
