import { OG_IMAGE } from '@/lib/site'

export const INSIGHT_SLUGS = [
  "fractional-coo",
  "strategic-planning",
  "process-optimization",
  "smb-digitization-benefits",
  "smb-digital-efficiency",
  "smb-digital-growth",
  "search-and-ai-visibility",
  "how-ai-systems-understand-websites",
  "structured-data-for-small-business",
  "professional-email-avoid-spam-phishing",
  "authentic-professional-portrait-selection",
  "website-portal-or-custom-app",
  "what-to-automate-first",
  "website-redesign-or-conversion-refresh",
  "build-buy-or-integrate-technology",
  "website-after-launch",
  "trade-show-leads-after-qr-scan",
  "workshop-consultant-or-fractional-leader",
  "practical-ai-use-cases",
  "founder-decision-bottleneck",
  "clear-decision-rights",
  "90-day-plan-vs-five-year-strategy",
  "process-problems-and-ownership",
  "team-change-readiness",
  "questions-before-choosing-business-platform",
  "what-technology-advisor-does",
  "compare-technology-proposals",
  "business-continuity-basics",
  "small-business-cybersecurity-priorities",
  "what-clients-check-before-booking",
  "website-traffic-not-inquiries",
  "contact-form-friction",
  "credible-service-page",
  "should-your-website-show-prices",
  "accessibility-is-customer-experience",
  "hidden-cost-of-copying-information",
  "automation-needs-exception-owner",
  "need-crm-or-better-tools",
  "disconnected-customer-systems",
  "automation-business-case",
  "smallest-useful-digital-product",
  "why-software-projects-grow",
  "spreadsheet-to-business-application",
  "what-customer-portal-can-solve",
  "validate-digital-product-before-build",
  "workshop-vs-another-meeting",
  "why-training-does-not-change-behaviour",
  "workshop-to-30-days-of-action",
  "prepare-strategic-planning-workshop",
  "ideation-too-many-ideas",
  "is-your-website-builder-limiting-growth",
  "free-website-builder-seo-ai-visibility-tradeoffs",
] as const;

export type InsightSlug = (typeof INSIGHT_SLUGS)[number];

export type InsightGroup = "digital" | "advisory";

/** Articles grouped for the header and insights index. Order is the reading order in each group. */
export const INSIGHT_GROUPS: Record<InsightGroup, readonly InsightSlug[]> = {
  digital: [
    "smb-digitization-benefits",
    "smb-digital-efficiency",
    "smb-digital-growth",
    "search-and-ai-visibility",
    "how-ai-systems-understand-websites",
    "structured-data-for-small-business",
    "professional-email-avoid-spam-phishing",
    "authentic-professional-portrait-selection",
    "website-portal-or-custom-app",
    "what-to-automate-first",
    "website-redesign-or-conversion-refresh",
    "website-after-launch",
    "trade-show-leads-after-qr-scan",
    "practical-ai-use-cases",
    "what-clients-check-before-booking",
    "website-traffic-not-inquiries",
    "contact-form-friction",
    "credible-service-page",
    "should-your-website-show-prices",
    "accessibility-is-customer-experience",
    "hidden-cost-of-copying-information",
    "automation-needs-exception-owner",
    "need-crm-or-better-tools",
    "disconnected-customer-systems",
    "automation-business-case",
    "smallest-useful-digital-product",
    "why-software-projects-grow",
    "spreadsheet-to-business-application",
    "what-customer-portal-can-solve",
    "validate-digital-product-before-build",
    "is-your-website-builder-limiting-growth",
    "free-website-builder-seo-ai-visibility-tradeoffs",
  ],
  advisory: ["fractional-coo", "strategic-planning", "process-optimization", "build-buy-or-integrate-technology", "workshop-consultant-or-fractional-leader", "founder-decision-bottleneck", "clear-decision-rights", "90-day-plan-vs-five-year-strategy", "process-problems-and-ownership", "team-change-readiness", "questions-before-choosing-business-platform", "what-technology-advisor-does", "compare-technology-proposals", "business-continuity-basics", "small-business-cybersecurity-priorities", "workshop-vs-another-meeting", "why-training-does-not-change-behaviour", "workshop-to-30-days-of-action", "prepare-strategic-planning-workshop", "ideation-too-many-ideas"],
};

/**
 * Fallback when an admin has not saved a header selection in the hub.
 * The live menu reads the saved selection; this list is the default.
 */
export const HEADER_INSIGHT_SLUGS = [
  "free-website-builder-seo-ai-visibility-tradeoffs",
  "professional-email-avoid-spam-phishing",
  "search-and-ai-visibility",
  "fractional-coo",
  "strategic-planning",
] as const satisfies readonly InsightSlug[];

export function headerInsightsForGroup(
  group: InsightGroup,
  selected: readonly InsightSlug[] = HEADER_INSIGHT_SLUGS,
): InsightSlug[] {
  const inGroup = new Set(INSIGHT_GROUPS[group]);
  return selected.filter((slug) => inGroup.has(slug));
}

export function isInsightSlug(value: string): value is InsightSlug {
  return (INSIGHT_SLUGS as readonly string[]).includes(value);
}

/** Optional per-article social preview images (defaults to site OG image). */
export const INSIGHT_OG_IMAGES: Partial<Record<InsightSlug, string>> = {
  "fractional-coo": "/images/insights/library/fractional-coo.webp",
  "strategic-planning": "/images/insights/library/strategic-planning.webp",
  "process-optimization": "/images/insights/library/process-optimization.webp",
  "smb-digitization-benefits": "/images/insights/library/smb-digitization-benefits.webp",
  "smb-digital-efficiency": "/images/insights/library/smb-digital-efficiency.webp",
  "smb-digital-growth": "/images/insights/library/smb-digital-growth.webp",
  "search-and-ai-visibility": "/images/insights/library/search-and-ai-visibility.webp",
  "how-ai-systems-understand-websites": "/images/insights/library/how-ai-systems-understand-websites.webp",
  "structured-data-for-small-business": "/images/insights/library/structured-data-for-small-business.webp",
  "professional-email-avoid-spam-phishing": "/images/insights/library/professional-email-avoid-spam-phishing.webp",
  "authentic-professional-portrait-selection": "/images/insights/library/authentic-professional-portrait-selection.webp",
  "website-portal-or-custom-app": "/images/insights/library/website-portal-or-custom-app.webp",
  "what-to-automate-first": "/images/insights/library/what-to-automate-first.webp",
  "website-redesign-or-conversion-refresh": "/images/insights/library/website-redesign-or-conversion-refresh.webp",
  "build-buy-or-integrate-technology": "/images/insights/library/build-buy-or-integrate-technology.webp",
  "website-after-launch": "/images/insights/library/website-after-launch.webp",
  "trade-show-leads-after-qr-scan": "/images/insights/library/trade-show-leads-after-qr-scan.webp",
  "workshop-consultant-or-fractional-leader": "/images/insights/library/workshop-consultant-or-fractional-leader.webp",
  "practical-ai-use-cases": "/images/insights/library/practical-ai-use-cases.webp",
  "founder-decision-bottleneck": "/images/insights/library/fractional-coo.webp",
  "clear-decision-rights": "/images/insights/library/strategic-planning.webp",
  "90-day-plan-vs-five-year-strategy": "/images/insights/library/strategic-planning.webp",
  "process-problems-and-ownership": "/images/insights/library/process-optimization.webp",
  "team-change-readiness": "/images/insights/library/workshop-consultant-or-fractional-leader.webp",
  "questions-before-choosing-business-platform": "/images/insights/library/build-buy-or-integrate-technology.webp",
  "what-technology-advisor-does": "/images/insights/library/build-buy-or-integrate-technology.webp",
  "compare-technology-proposals": "/images/insights/library/build-buy-or-integrate-technology.webp",
  "business-continuity-basics": "/images/insights/library/professional-email-avoid-spam-phishing.webp",
  "small-business-cybersecurity-priorities": "/images/insights/library/professional-email-avoid-spam-phishing.webp",
  "what-clients-check-before-booking": "/images/insights/library/authentic-professional-portrait-selection.webp",
  "website-traffic-not-inquiries": "/images/insights/library/website-redesign-or-conversion-refresh.webp",
  "contact-form-friction": "/images/insights/library/website-redesign-or-conversion-refresh.webp",
  "credible-service-page": "/images/insights/website-builder-growth/website-builder-growth-hero.webp",
  "should-your-website-show-prices": "/images/insights/website-builder-growth/website-builder-growth-hero.webp",
  "accessibility-is-customer-experience": "/images/insights/library/website-after-launch.webp",
  "hidden-cost-of-copying-information": "/images/insights/library/what-to-automate-first.webp",
  "automation-needs-exception-owner": "/images/insights/library/what-to-automate-first.webp",
  "need-crm-or-better-tools": "/images/insights/library/smb-digital-efficiency.webp",
  "disconnected-customer-systems": "/images/insights/library/smb-digital-growth.webp",
  "automation-business-case": "/images/insights/library/what-to-automate-first.webp",
  "smallest-useful-digital-product": "/images/insights/library/website-portal-or-custom-app.webp",
  "why-software-projects-grow": "/images/insights/library/website-portal-or-custom-app.webp",
  "spreadsheet-to-business-application": "/images/insights/library/smb-digitization-benefits.webp",
  "what-customer-portal-can-solve": "/images/insights/library/website-portal-or-custom-app.webp",
  "validate-digital-product-before-build": "/images/insights/library/website-portal-or-custom-app.webp",
  "workshop-vs-another-meeting": "/images/insights/library/workshop-consultant-or-fractional-leader.webp",
  "why-training-does-not-change-behaviour": "/images/insights/library/workshop-consultant-or-fractional-leader.webp",
  "workshop-to-30-days-of-action": "/images/insights/library/workshop-consultant-or-fractional-leader.webp",
  "prepare-strategic-planning-workshop": "/images/insights/library/strategic-planning.webp",
  "ideation-too-many-ideas": "/images/insights/library/workshop-consultant-or-fractional-leader.webp",
  "free-website-builder-seo-ai-visibility-tradeoffs": "/images/insights/library/is-your-website-builder-limiting-growth.webp",
};

/** Insights rooted in delivery work — shown with an engagement chip on the homepage */
export const INSIGHT_ENGAGEMENT_SLUGS: readonly InsightSlug[] = [
  "smb-digitization-benefits",
  "smb-digital-efficiency",
  "smb-digital-growth",
  "search-and-ai-visibility",
  "process-optimization",
];

export function insightCoverImage(slug: InsightSlug): string {
  return INSIGHT_OG_IMAGES[slug] ?? OG_IMAGE;
}

export function insightFromEngagement(slug: InsightSlug): boolean {
  return INSIGHT_ENGAGEMENT_SLUGS.includes(slug);
}

export const INSIGHT_PUBLISHED_DATES: Record<InsightSlug, string> = {
  "fractional-coo": "2025-11-01",
  "strategic-planning": "2025-12-01",
  "process-optimization": "2026-01-15",
  "smb-digitization-benefits": "2026-02-01",
  "smb-digital-efficiency": "2026-03-01",
  "smb-digital-growth": "2026-04-01",
  "search-and-ai-visibility": "2026-05-01",
  "how-ai-systems-understand-websites": "2026-07-15",
  "structured-data-for-small-business": "2026-07-22",
  "professional-email-avoid-spam-phishing": "2026-09-26",
  "authentic-professional-portrait-selection": "2026-09-26",
  "website-portal-or-custom-app": "2026-09-27",
  "what-to-automate-first": "2026-09-27",
  "website-redesign-or-conversion-refresh": "2026-09-27",
  "build-buy-or-integrate-technology": "2026-09-27",
  "website-after-launch": "2026-09-27",
  "trade-show-leads-after-qr-scan": "2026-09-27",
  "workshop-consultant-or-fractional-leader": "2026-09-27",
  "practical-ai-use-cases": "2026-09-27",
  "founder-decision-bottleneck": "2026-09-27",
  "clear-decision-rights": "2026-09-27",
  "90-day-plan-vs-five-year-strategy": "2026-09-27",
  "process-problems-and-ownership": "2026-09-27",
  "team-change-readiness": "2026-09-27",
  "questions-before-choosing-business-platform": "2026-09-27",
  "what-technology-advisor-does": "2026-09-27",
  "compare-technology-proposals": "2026-09-27",
  "business-continuity-basics": "2026-09-27",
  "small-business-cybersecurity-priorities": "2026-09-27",
  "what-clients-check-before-booking": "2026-09-27",
  "website-traffic-not-inquiries": "2026-09-27",
  "contact-form-friction": "2026-09-27",
  "credible-service-page": "2026-09-27",
  "should-your-website-show-prices": "2026-09-27",
  "accessibility-is-customer-experience": "2026-09-27",
  "hidden-cost-of-copying-information": "2026-09-27",
  "automation-needs-exception-owner": "2026-09-27",
  "need-crm-or-better-tools": "2026-09-27",
  "disconnected-customer-systems": "2026-09-27",
  "automation-business-case": "2026-09-27",
  "smallest-useful-digital-product": "2026-09-27",
  "why-software-projects-grow": "2026-09-27",
  "spreadsheet-to-business-application": "2026-09-27",
  "what-customer-portal-can-solve": "2026-09-27",
  "validate-digital-product-before-build": "2026-09-27",
  "workshop-vs-another-meeting": "2026-09-27",
  "why-training-does-not-change-behaviour": "2026-09-27",
  "workshop-to-30-days-of-action": "2026-09-27",
  "prepare-strategic-planning-workshop": "2026-09-27",
  "ideation-too-many-ideas": "2026-09-27",
  "is-your-website-builder-limiting-growth": "2026-09-26",
  "free-website-builder-seo-ai-visibility-tradeoffs": "2026-09-28",
};
