import { OG_IMAGE } from '@/lib/site'

export const INSIGHT_SLUGS = [
  "fractional-coo",
  "strategic-planning",
  "process-optimization",
  "smb-digitization-benefits",
  "smb-digital-efficiency",
  "smb-digital-growth",
  "search-and-ai-visibility",
  "geo-seo-aeo-and-bots",
  "how-ai-systems-understand-websites",
  "structured-data-for-small-business",
  "professional-email-avoid-spam-phishing",
  "authentic-professional-portrait-selection",
  "website-portal-or-custom-app",
  "what-to-automate-first",
  "website-redesign-or-conversion-refresh",
  "build-buy-or-integrate-technology",
  "website-after-launch",
  "trade-show-leads-after-qr-scan",
  "workshop-consultant-or-fractional-leader",
  "practical-ai-use-cases",
  "founder-decision-bottleneck",
  "clear-decision-rights",
  "90-day-plan-vs-five-year-strategy",
  "process-problems-and-ownership",
  "team-change-readiness",
  "questions-before-choosing-business-platform",
  "what-technology-advisor-does",
  "compare-technology-proposals",
  "business-continuity-basics",
  "small-business-cybersecurity-priorities",
  "what-clients-check-before-booking",
  "website-traffic-not-inquiries",
  "contact-form-friction",
  "credible-service-page",
  "should-your-website-show-prices",
  "accessibility-is-customer-experience",
  "hidden-cost-of-copying-information",
  "automation-needs-exception-owner",
  "need-crm-or-better-tools",
  "disconnected-customer-systems",
  "automation-business-case",
  "smallest-useful-digital-product",
  "why-software-projects-grow",
  "spreadsheet-to-business-application",
  "what-customer-portal-can-solve",
  "validate-digital-product-before-build",
  "workshop-vs-another-meeting",
  "why-training-does-not-change-behaviour",
  "workshop-to-30-days-of-action",
  "prepare-strategic-planning-workshop",
  "ideation-too-many-ideas",
  "is-your-website-builder-limiting-growth",
  "free-website-builder-seo-ai-visibility-tradeoffs",
  "contrast-text-size-accessibility-conversion",
  "networking-roi-solopreneurs-small-business",
  "should-you-say-yes-to-this-opportunity",
  "hire-or-fix-the-work-first",
  "revenue-growing-why-not-more-cash",
  "what-if-biggest-client-leaves",
  "turn-custom-service-into-repeatable-offer",
  "sales-pipeline-or-list-of-contacts",
  "owner-is-the-capacity-problem",
  "which-customers-are-actually-profitable",
  "minimum-monthly-owner-dashboard",
  "what-should-you-stop-doing-this-quarter",
  "can-business-operate-two-weeks-without-you",
  "client-boundaries-without-damaging-relationships",
  "meetings-moving-business-or-reporting-past",
  "when-solopreneur-should-form-partnership",
  "building-business-or-demanding-job",
  "five-rules-before-team-uses-ai",
  "data-ownership-leaving-software-platform",
  "software-subscription-stack-audit",
  "cloud-backup-sync-recovery-differences",
  "it-provider-who-owns-risk",
  "twelve-month-technology-roadmap",
  "data-ready-for-automation",
  "measure-software-business-value",
  "personal-information-stop-collecting",
  "technology-renewal-checklist",
  "consolidate-systems-before-soc-2-readiness",
  "analog-to-ip-business-telephony",
  "what-to-expect-soc-2-examination-saas",
  "website-optimized-search-analytics-90-day-review",
] as const;

export type InsightSlug = (typeof INSIGHT_SLUGS)[number];

export type InsightGroup = "digital" | "advisory";
export type InsightBrowserArea = "digital" | "business" | "technology";

/** Articles grouped for the header and insights index. Order is the reading order in each group. */
export const INSIGHT_GROUPS: Record<InsightGroup, readonly InsightSlug[]> = {
  digital: [
    "smb-digitization-benefits",
    "smb-digital-efficiency",
    "smb-digital-growth",
    "search-and-ai-visibility",
    "website-optimized-search-analytics-90-day-review",
    "geo-seo-aeo-and-bots",
    "how-ai-systems-understand-websites",
    "structured-data-for-small-business",
    "professional-email-avoid-spam-phishing",
    "authentic-professional-portrait-selection",
    "website-portal-or-custom-app",
    "what-to-automate-first",
    "website-redesign-or-conversion-refresh",
    "website-after-launch",
    "trade-show-leads-after-qr-scan",
    "practical-ai-use-cases",
    "what-clients-check-before-booking",
    "website-traffic-not-inquiries",
    "contact-form-friction",
    "credible-service-page",
    "should-your-website-show-prices",
    "accessibility-is-customer-experience",
    "hidden-cost-of-copying-information",
    "automation-needs-exception-owner",
    "need-crm-or-better-tools",
    "disconnected-customer-systems",
    "automation-business-case",
    "smallest-useful-digital-product",
    "why-software-projects-grow",
    "spreadsheet-to-business-application",
    "what-customer-portal-can-solve",
    "validate-digital-product-before-build",
    "is-your-website-builder-limiting-growth",
    "free-website-builder-seo-ai-visibility-tradeoffs",
    "contrast-text-size-accessibility-conversion",
  ],
  advisory: ["which-customers-are-actually-profitable", "minimum-monthly-owner-dashboard", "what-should-you-stop-doing-this-quarter", "can-business-operate-two-weeks-without-you", "client-boundaries-without-damaging-relationships", "meetings-moving-business-or-reporting-past", "when-solopreneur-should-form-partnership", "building-business-or-demanding-job", "should-you-say-yes-to-this-opportunity", "hire-or-fix-the-work-first", "revenue-growing-why-not-more-cash", "what-if-biggest-client-leaves", "turn-custom-service-into-repeatable-offer", "sales-pipeline-or-list-of-contacts", "owner-is-the-capacity-problem", "networking-roi-solopreneurs-small-business", "five-rules-before-team-uses-ai", "data-ownership-leaving-software-platform", "software-subscription-stack-audit", "cloud-backup-sync-recovery-differences", "it-provider-who-owns-risk", "twelve-month-technology-roadmap", "data-ready-for-automation", "measure-software-business-value", "personal-information-stop-collecting", "technology-renewal-checklist", "consolidate-systems-before-soc-2-readiness", "what-to-expect-soc-2-examination-saas", "analog-to-ip-business-telephony", "fractional-coo", "strategic-planning", "process-optimization", "build-buy-or-integrate-technology", "workshop-consultant-or-fractional-leader", "founder-decision-bottleneck", "clear-decision-rights", "90-day-plan-vs-five-year-strategy", "process-problems-and-ownership", "team-change-readiness", "questions-before-choosing-business-platform", "what-technology-advisor-does", "compare-technology-proposals", "business-continuity-basics", "small-business-cybersecurity-priorities", "workshop-vs-another-meeting", "why-training-does-not-change-behaviour", "workshop-to-30-days-of-action", "prepare-strategic-planning-workshop", "ideation-too-many-ideas"],
};

/** Advisory articles whose subject is technology, security, data, or solution sourcing. */
export const ADVISORY_TECHNOLOGY_SLUGS = [
  "five-rules-before-team-uses-ai",
  "data-ownership-leaving-software-platform",
  "software-subscription-stack-audit",
  "cloud-backup-sync-recovery-differences",
  "it-provider-who-owns-risk",
  "twelve-month-technology-roadmap",
  "data-ready-for-automation",
  "measure-software-business-value",
  "personal-information-stop-collecting",
  "technology-renewal-checklist",
  "consolidate-systems-before-soc-2-readiness",
  "what-to-expect-soc-2-examination-saas",
  "analog-to-ip-business-telephony",
  "build-buy-or-integrate-technology",
  "questions-before-choosing-business-platform",
  "what-technology-advisor-does",
  "compare-technology-proposals",
  "business-continuity-basics",
  "small-business-cybersecurity-priorities",
] as const satisfies readonly InsightSlug[];

const ADVISORY_TECHNOLOGY = new Set<string>(ADVISORY_TECHNOLOGY_SLUGS);

export function insightBrowserArea(slug: InsightSlug): InsightBrowserArea {
  if ((INSIGHT_GROUPS.digital as readonly string[]).includes(slug)) return "digital";
  if (ADVISORY_TECHNOLOGY.has(slug)) return "technology";
  return "business";
}

/**
 * Fallback when an admin has not saved a header selection in the hub.
 * The live menu reads the saved selection; this list is the default.
 */
export const HEADER_INSIGHT_SLUGS = [
  "networking-roi-solopreneurs-small-business",
  "professional-email-avoid-spam-phishing",
  "search-and-ai-visibility",
  "fractional-coo",
  "strategic-planning",
] as const satisfies readonly InsightSlug[];

export function headerInsightsForGroup(
  group: InsightGroup,
  selected: readonly InsightSlug[] = HEADER_INSIGHT_SLUGS,
): InsightSlug[] {
  const inGroup = new Set(INSIGHT_GROUPS[group]);
  return selected.filter((slug) => inGroup.has(slug));
}

export function isInsightSlug(value: string): value is InsightSlug {
  return (INSIGHT_SLUGS as readonly string[]).includes(value);
}

/** Optional per-article social preview images (defaults to site OG image). */
export const INSIGHT_OG_IMAGES: Partial<Record<InsightSlug, string>> = {
  "fractional-coo": "/images/insights/library/fractional-coo.webp",
  "strategic-planning": "/images/insights/library/strategic-planning.webp",
  "process-optimization": "/images/insights/library/process-optimization.webp",
  "smb-digitization-benefits": "/images/insights/library/smb-digitization-benefits.webp",
  "smb-digital-efficiency": "/images/insights/library/smb-digital-efficiency.webp",
  "smb-digital-growth": "/images/insights/library/smb-digital-growth.webp",
  "search-and-ai-visibility": "/images/insights/library/search-and-ai-visibility.webp",
  "geo-seo-aeo-and-bots": "/images/insights/library/search-and-ai-visibility.webp",
  "how-ai-systems-understand-websites": "/images/insights/library/how-ai-systems-understand-websites.webp",
  "structured-data-for-small-business": "/images/insights/library/structured-data-for-small-business.webp",
  "professional-email-avoid-spam-phishing": "/images/insights/library/professional-email-avoid-spam-phishing.webp",
  "authentic-professional-portrait-selection": "/images/insights/library/authentic-professional-portrait-selection.webp",
  "website-portal-or-custom-app": "/images/insights/library/website-portal-or-custom-app.webp",
  "what-to-automate-first": "/images/insights/library/what-to-automate-first.webp",
  "website-redesign-or-conversion-refresh": "/images/insights/library/website-redesign-or-conversion-refresh.webp",
  "build-buy-or-integrate-technology": "/images/insights/library/build-buy-or-integrate-technology.webp",
  "website-after-launch": "/images/insights/library/website-after-launch.webp",
  "trade-show-leads-after-qr-scan": "/images/insights/library/trade-show-leads-after-qr-scan.webp",
  "workshop-consultant-or-fractional-leader": "/images/insights/library/workshop-consultant-or-fractional-leader.webp",
  "practical-ai-use-cases": "/images/insights/library/practical-ai-use-cases.webp",
  "founder-decision-bottleneck": "/images/insights/library/fractional-coo.webp",
  "clear-decision-rights": "/images/insights/library/strategic-planning.webp",
  "90-day-plan-vs-five-year-strategy": "/images/insights/library/strategic-planning.webp",
  "process-problems-and-ownership": "/images/insights/library/process-optimization.webp",
  "team-change-readiness": "/images/insights/library/workshop-consultant-or-fractional-leader.webp",
  "questions-before-choosing-business-platform": "/images/insights/library/build-buy-or-integrate-technology.webp",
  "what-technology-advisor-does": "/images/insights/library/build-buy-or-integrate-technology.webp",
  "compare-technology-proposals": "/images/insights/library/build-buy-or-integrate-technology.webp",
  "business-continuity-basics": "/images/insights/library/professional-email-avoid-spam-phishing.webp",
  "small-business-cybersecurity-priorities": "/images/insights/library/professional-email-avoid-spam-phishing.webp",
  "what-clients-check-before-booking": "/images/insights/library/authentic-professional-portrait-selection.webp",
  "website-traffic-not-inquiries": "/images/insights/library/website-redesign-or-conversion-refresh.webp",
  "contact-form-friction": "/images/insights/library/website-redesign-or-conversion-refresh.webp",
  "credible-service-page": "/images/insights/website-builder-growth/website-builder-growth-hero.webp",
  "should-your-website-show-prices": "/images/insights/website-builder-growth/website-builder-growth-hero.webp",
  "accessibility-is-customer-experience": "/images/insights/library/website-after-launch.webp",
  "hidden-cost-of-copying-information": "/images/insights/library/what-to-automate-first.webp",
  "automation-needs-exception-owner": "/images/insights/library/what-to-automate-first.webp",
  "need-crm-or-better-tools": "/images/insights/library/smb-digital-efficiency.webp",
  "disconnected-customer-systems": "/images/insights/library/smb-digital-growth.webp",
  "automation-business-case": "/images/insights/library/what-to-automate-first.webp",
  "smallest-useful-digital-product": "/images/insights/library/website-portal-or-custom-app.webp",
  "why-software-projects-grow": "/images/insights/library/website-portal-or-custom-app.webp",
  "spreadsheet-to-business-application": "/images/insights/library/smb-digitization-benefits.webp",
  "what-customer-portal-can-solve": "/images/insights/library/website-portal-or-custom-app.webp",
  "validate-digital-product-before-build": "/images/insights/library/website-portal-or-custom-app.webp",
  "workshop-vs-another-meeting": "/images/insights/library/workshop-consultant-or-fractional-leader.webp",
  "why-training-does-not-change-behaviour": "/images/insights/library/workshop-consultant-or-fractional-leader.webp",
  "workshop-to-30-days-of-action": "/images/insights/library/workshop-consultant-or-fractional-leader.webp",
  "prepare-strategic-planning-workshop": "/images/insights/library/strategic-planning.webp",
  "ideation-too-many-ideas": "/images/insights/library/workshop-consultant-or-fractional-leader.webp",
  "free-website-builder-seo-ai-visibility-tradeoffs": "/images/insights/library/is-your-website-builder-limiting-growth.webp",
  "contrast-text-size-accessibility-conversion": "/images/insights/library/contrast-text-size-accessibility-conversion.webp",
  "networking-roi-solopreneurs-small-business": "/images/insights/library/networking-roi-solopreneurs-small-business.webp",
  "should-you-say-yes-to-this-opportunity": "/images/insights/library/should-you-say-yes-to-this-opportunity.webp",
  "hire-or-fix-the-work-first": "/images/insights/library/hire-or-fix-the-work-first.webp",
  "revenue-growing-why-not-more-cash": "/images/insights/library/revenue-growing-why-not-more-cash.webp",
  "what-if-biggest-client-leaves": "/images/insights/library/what-if-biggest-client-leaves.webp",
  "turn-custom-service-into-repeatable-offer": "/images/insights/library/turn-custom-service-into-repeatable-offer.webp",
  "sales-pipeline-or-list-of-contacts": "/images/insights/library/sales-pipeline-or-list-of-contacts.webp",
  "owner-is-the-capacity-problem": "/images/insights/library/owner-is-the-capacity-problem.webp",
  "which-customers-are-actually-profitable": "/images/insights/library/which-customers-are-actually-profitable.webp",
  "minimum-monthly-owner-dashboard": "/images/insights/library/minimum-monthly-owner-dashboard.webp",
  "what-should-you-stop-doing-this-quarter": "/images/insights/library/what-should-you-stop-doing-this-quarter.webp",
  "can-business-operate-two-weeks-without-you": "/images/insights/library/can-business-operate-two-weeks-without-you.webp",
  "client-boundaries-without-damaging-relationships": "/images/insights/library/client-boundaries-without-damaging-relationships.webp",
  "meetings-moving-business-or-reporting-past": "/images/insights/library/meetings-moving-business-or-reporting-past.webp",
  "when-solopreneur-should-form-partnership": "/images/insights/library/when-solopreneur-should-form-partnership.webp",
  "building-business-or-demanding-job": "/images/insights/library/building-business-or-demanding-job.webp",
  "five-rules-before-team-uses-ai": "/images/insights/library/five-rules-before-team-uses-ai.webp",
  "data-ownership-leaving-software-platform": "/images/insights/library/data-ownership-leaving-software-platform.webp",
  "software-subscription-stack-audit": "/images/insights/library/software-subscription-stack-audit.webp",
  "cloud-backup-sync-recovery-differences": "/images/insights/library/cloud-backup-sync-recovery-differences.webp",
  "it-provider-who-owns-risk": "/images/insights/library/it-provider-who-owns-risk.webp",
  "twelve-month-technology-roadmap": "/images/insights/library/twelve-month-technology-roadmap.webp",
  "data-ready-for-automation": "/images/insights/library/data-ready-for-automation.webp",
  "measure-software-business-value": "/images/insights/library/measure-software-business-value.webp",
  "personal-information-stop-collecting": "/images/insights/library/personal-information-stop-collecting.webp",
  "technology-renewal-checklist": "/images/insights/library/technology-renewal-checklist.webp",
  "consolidate-systems-before-soc-2-readiness": "/images/insights/library/consolidate-systems-before-soc-2-readiness.webp",
  "analog-to-ip-business-telephony": "/images/insights/library/analog-to-ip-business-telephony.webp",
  "what-to-expect-soc-2-examination-saas": "/images/insights/library/what-to-expect-soc-2-examination-saas.webp",
  "website-optimized-search-analytics-90-day-review": "/images/insights/library/website-optimized-search-analytics-90-day-review.webp",
};

/** Insights rooted in delivery work — shown with an engagement chip on the homepage */
export const INSIGHT_ENGAGEMENT_SLUGS: readonly InsightSlug[] = [
  "smb-digitization-benefits",
  "smb-digital-efficiency",
  "smb-digital-growth",
  "search-and-ai-visibility",
  "process-optimization",
];

/** Homepage cards are ~380px wide. Serve a 2x file instead of the full OG image. */
export function insightCoverImage(slug: InsightSlug): string {
  const full = INSIGHT_OG_IMAGES[slug]
  if (!full) return OG_IMAGE
  return full.replace('/images/insights/library/', '/images/insights/cards/')
}

export function insightFromEngagement(slug: InsightSlug): boolean {
  return INSIGHT_ENGAGEMENT_SLUGS.includes(slug);
}

export const INSIGHT_PUBLISHED_DATES: Record<InsightSlug, string> = {
  "fractional-coo": "2025-11-01",
  "strategic-planning": "2025-12-01",
  "process-optimization": "2026-01-15",
  "smb-digitization-benefits": "2026-02-01",
  "smb-digital-efficiency": "2026-03-01",
  "smb-digital-growth": "2026-04-01",
  "search-and-ai-visibility": "2026-05-01",
  "geo-seo-aeo-and-bots": "2026-09-28",
  "how-ai-systems-understand-websites": "2026-07-15",
  "structured-data-for-small-business": "2026-07-22",
  "professional-email-avoid-spam-phishing": "2026-09-26",
  "authentic-professional-portrait-selection": "2026-09-26",
  "website-portal-or-custom-app": "2026-09-27",
  "what-to-automate-first": "2026-09-27",
  "website-redesign-or-conversion-refresh": "2026-09-27",
  "build-buy-or-integrate-technology": "2026-09-27",
  "website-after-launch": "2026-09-27",
  "trade-show-leads-after-qr-scan": "2026-09-27",
  "workshop-consultant-or-fractional-leader": "2026-09-27",
  "practical-ai-use-cases": "2026-09-27",
  "founder-decision-bottleneck": "2026-09-27",
  "clear-decision-rights": "2026-09-27",
  "90-day-plan-vs-five-year-strategy": "2026-09-27",
  "process-problems-and-ownership": "2026-09-27",
  "team-change-readiness": "2026-09-27",
  "questions-before-choosing-business-platform": "2026-09-27",
  "what-technology-advisor-does": "2026-09-27",
  "compare-technology-proposals": "2026-09-27",
  "business-continuity-basics": "2026-09-27",
  "small-business-cybersecurity-priorities": "2026-09-27",
  "what-clients-check-before-booking": "2026-09-27",
  "website-traffic-not-inquiries": "2026-09-27",
  "contact-form-friction": "2026-09-27",
  "credible-service-page": "2026-09-27",
  "should-your-website-show-prices": "2026-09-27",
  "accessibility-is-customer-experience": "2026-09-27",
  "hidden-cost-of-copying-information": "2026-09-27",
  "automation-needs-exception-owner": "2026-09-27",
  "need-crm-or-better-tools": "2026-09-27",
  "disconnected-customer-systems": "2026-09-27",
  "automation-business-case": "2026-09-27",
  "smallest-useful-digital-product": "2026-09-27",
  "why-software-projects-grow": "2026-09-27",
  "spreadsheet-to-business-application": "2026-09-27",
  "what-customer-portal-can-solve": "2026-09-27",
  "validate-digital-product-before-build": "2026-09-27",
  "workshop-vs-another-meeting": "2026-09-27",
  "why-training-does-not-change-behaviour": "2026-09-27",
  "workshop-to-30-days-of-action": "2026-09-27",
  "prepare-strategic-planning-workshop": "2026-09-27",
  "ideation-too-many-ideas": "2026-09-27",
  "is-your-website-builder-limiting-growth": "2026-09-26",
  "free-website-builder-seo-ai-visibility-tradeoffs": "2026-09-28",
  "contrast-text-size-accessibility-conversion": "2026-09-28",
  "networking-roi-solopreneurs-small-business": "2026-09-28",
  "should-you-say-yes-to-this-opportunity": "2026-09-28",
  "hire-or-fix-the-work-first": "2026-09-28",
  "revenue-growing-why-not-more-cash": "2026-09-28",
  "what-if-biggest-client-leaves": "2026-09-28",
  "turn-custom-service-into-repeatable-offer": "2026-09-28",
  "sales-pipeline-or-list-of-contacts": "2026-09-28",
  "owner-is-the-capacity-problem": "2026-09-28",
  "which-customers-are-actually-profitable": "2026-09-28",
  "minimum-monthly-owner-dashboard": "2026-09-28",
  "what-should-you-stop-doing-this-quarter": "2026-09-28",
  "can-business-operate-two-weeks-without-you": "2026-09-28",
  "client-boundaries-without-damaging-relationships": "2026-09-28",
  "meetings-moving-business-or-reporting-past": "2026-09-28",
  "when-solopreneur-should-form-partnership": "2026-09-28",
  "building-business-or-demanding-job": "2026-09-28",
  "five-rules-before-team-uses-ai": "2026-09-28",
  "data-ownership-leaving-software-platform": "2026-09-28",
  "software-subscription-stack-audit": "2026-09-28",
  "cloud-backup-sync-recovery-differences": "2026-09-28",
  "it-provider-who-owns-risk": "2026-09-28",
  "twelve-month-technology-roadmap": "2026-09-28",
  "data-ready-for-automation": "2026-09-28",
  "measure-software-business-value": "2026-09-28",
  "personal-information-stop-collecting": "2026-09-28",
  "technology-renewal-checklist": "2026-09-28",
  "consolidate-systems-before-soc-2-readiness": "2026-09-28",
  "analog-to-ip-business-telephony": "2026-09-29",
  "what-to-expect-soc-2-examination-saas": "2026-09-29",
  "website-optimized-search-analytics-90-day-review": "2026-09-29",
};
