import { test, expect } from '@playwright/test'

test.describe('Digital creations portfolio order', () => {
  test('hero, jump nav, and all projects list platforms first', async ({ page }) => {
    await page.goto('/en/services/portfolio')

    const heroLinks = page.locator('main header a[href^="https://"]')
    await expect(heroLinks.nth(0)).toContainText('businesscocoon.com')
    await expect(heroLinks.nth(1)).toContainText('grcstatus.com')
    await expect(heroLinks.nth(2)).toContainText('4theblueprint.com')
    await expect(heroLinks.nth(3)).toContainText('boothlio.com')
    await expect(heroLinks.nth(4)).toContainText('valentir.ca')
    await expect(heroLinks.nth(5)).toContainText('my360vision.com')
    await expect(heroLinks.nth(6)).toContainText('soaringpuck.com')
    await expect(heroLinks.nth(7)).toContainText('pitchhotshot.com')
    await expect(heroLinks.nth(8)).toContainText('keneffect.com')
    await expect(heroLinks.nth(9)).toContainText('goaliestop.com')
    await expect(heroLinks.nth(10)).toContainText('coldbru.dejabru.ca')
    await expect(heroLinks.nth(11)).toContainText('roalla.com')

    const jumpNav = page.getByRole('navigation', { name: 'Jump to project' })
    const jumpLinks = jumpNav.getByRole('link')
    await expect(jumpLinks.nth(0)).toHaveText(/Business Cocoon/i)
    await expect(jumpLinks.nth(1)).toHaveText(/GRCStatus/i)
    await expect(jumpLinks.nth(2)).toHaveText(/4 The Blueprint/i)
    await expect(jumpLinks.nth(3)).toHaveText(/Boothlio/i)
    await expect(jumpLinks.nth(4)).toHaveText(/Valentir Green Tech/i)
    await expect(jumpLinks.nth(5)).toHaveText(/My360Vision/i)
    await expect(jumpLinks.nth(6)).toHaveText(/Soaring Puck/i)
    await expect(jumpLinks.nth(7)).toHaveText(/Pitch Hotshots/i)
    await expect(jumpLinks.nth(8)).toHaveText(/Ken Effect/i)
    await expect(jumpLinks.nth(9)).toHaveText(/Goalie Stop/i)
    await expect(jumpLinks.nth(10)).toHaveText(/Cold Deja Bru/i)
    await expect(jumpLinks.nth(11)).toHaveText(/ROALLA/i)

    const projectCards = page.locator('#portfolio article h3')
    await expect(projectCards.nth(0)).toHaveText(/GRCStatus/i)
    await expect(projectCards.nth(1)).toHaveText(/4 The Blueprint/i)
    await expect(projectCards.nth(2)).toHaveText(/Boothlio/i)
    await expect(projectCards.nth(3)).toHaveText(/My360Vision/i)
    await expect(projectCards.nth(4)).toHaveText(/Soaring Puck/i)
    await expect(projectCards.nth(5)).toHaveText(/Pitch Hotshots/i)
    await expect(projectCards.nth(6)).toHaveText(/Ken Effect/i)
    await expect(projectCards.nth(7)).toHaveText(/Goalie Stop/i)
    await expect(projectCards.nth(8)).toHaveText(/Cold Deja Bru/i)
    await expect(projectCards.nth(9)).toHaveText(/ROALLA/i)
  })
})
