"use client";

import React, { useMemo, useState } from "react";
import { ArrowRight, Calculator, Clock3, MousePointerClick, Users } from "lucide-react";
import { annualAutomationValue, annualWebsiteOpportunity, eventFollowUpOpportunity } from "@/lib/digital-value-planner";
import { trackAnalyticsEvent } from "@/lib/analytics";

function NumberField({ label, value, onChange, suffix }: { label: string; value: number; onChange: (value: number) => void; suffix?: string }) {
  return <label className="block text-sm font-semibold text-slate-800"><span>{label}</span><span className="relative mt-2 block"><input type="number" min="0" step="any" value={value} onChange={(event) => onChange(Number(event.target.value))} className="min-h-[46px] w-full rounded-lg border border-slate-300 px-3 pr-14 font-normal text-slate-950 outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" />{suffix ? <span className="pointer-events-none absolute right-3 top-3 text-sm text-slate-500">{suffix}</span> : null}</span></label>;
}

export default function BusinessValueCalculators({ locale }: { locale: string }) {
  const fr = locale === "fr";
  const money = useMemo(() => new Intl.NumberFormat(fr ? "fr-CA" : "en-CA", { style: "currency", currency: "CAD", maximumFractionDigits: 0 }), [fr]);
  const number = useMemo(() => new Intl.NumberFormat(fr ? "fr-CA" : "en-CA", { maximumFractionDigits: 1 }), [fr]);
  const [people, setPeople] = useState(2); const [hours, setHours] = useState(5); const [hourly, setHourly] = useState(40); const [reduction, setReduction] = useState(50);
  const [visitors, setVisitors] = useState(1000); const [currentRate, setCurrentRate] = useState(1); const [targetRate, setTargetRate] = useState(2); const [webClose, setWebClose] = useState(20); const [webValue, setWebValue] = useState(1000);
  const [leads, setLeads] = useState(100); const [currentFollow, setCurrentFollow] = useState(40); const [targetFollow, setTargetFollow] = useState(80); const [eventClose, setEventClose] = useState(10); const [eventValue, setEventValue] = useState(2000);
  const automation = annualAutomationValue({ people, hoursPerWeek: hours, hourlyCost: hourly, reductionPercent: reduction });
  const website = annualWebsiteOpportunity({ monthlyVisitors: visitors, currentInquiryRate: currentRate, targetInquiryRate: targetRate, closeRate: webClose, customerValue: webValue });
  const event = eventFollowUpOpportunity({ leads, currentFollowUpRate: currentFollow, targetFollowUpRate: targetFollow, closeRate: eventClose, customerValue: eventValue });
  const field = fr ? {
    people: "Personnes qui font ce travail", hours: "Heures par personne chaque semaine", hourly: "Coût horaire approximatif", reduction: "Part du travail possiblement réduite",
    visitors: "Visites mensuelles", currentRate: "Taux de demande actuel", targetRate: "Taux de demande visé", close: "Part des demandes qui deviennent clientes", customer: "Valeur moyenne d’un nouveau client",
    leads: "Contacts recueillis", currentFollow: "Suivis actuels", targetFollow: "Suivis visés",
  } : {
    people: "People doing this work", hours: "Hours per person each week", hourly: "Approximate hourly cost", reduction: "Share of work that may be reduced",
    visitors: "Monthly website visits", currentRate: "Current inquiry rate", targetRate: "Target inquiry rate", close: "Inquiries that become customers", customer: "Average value of a new customer",
    leads: "Contacts collected", currentFollow: "Contacts followed up today", targetFollow: "Target follow-up rate",
  };
  const cards = [
    { key: "automation", icon: Clock3, title: fr ? "Valeur possible de l’automatisation" : "Automation opportunity", intro: fr ? "Estimez la valeur annuelle du temps consacré à un flux répétitif." : "Estimate the annual value tied to time spent on one repetitive workflow.", inputs: <><NumberField label={field.people} value={people} onChange={setPeople} /><NumberField label={field.hours} value={hours} onChange={setHours} /><NumberField label={field.hourly} value={hourly} onChange={setHourly} suffix="$" /><NumberField label={field.reduction} value={reduction} onChange={setReduction} suffix="%" /></>, result: money.format(automation.potentialAnnualValue), detail: fr ? `Coût annuel actuel estimé : ${money.format(automation.currentAnnualCost)}` : `Estimated current annual cost: ${money.format(automation.currentAnnualCost)}`, href: `/${locale}/contact?intent=automation&goal=${encodeURIComponent("Automation calculator estimate: " + money.format(automation.potentialAnnualValue))}` },
    { key: "website", icon: MousePointerClick, title: fr ? "Possibilité de demandes du site" : "Website inquiry opportunity", intro: fr ? "Explorez ce qu’un petit changement du taux de demande pourrait représenter." : "Explore what a modest change in inquiry rate could mean.", inputs: <><NumberField label={field.visitors} value={visitors} onChange={setVisitors} /><NumberField label={field.currentRate} value={currentRate} onChange={setCurrentRate} suffix="%" /><NumberField label={field.targetRate} value={targetRate} onChange={setTargetRate} suffix="%" /><NumberField label={field.close} value={webClose} onChange={setWebClose} suffix="%" /><NumberField label={field.customer} value={webValue} onChange={setWebValue} suffix="$" /></>, result: money.format(website.potentialAnnualValue), detail: fr ? `${number.format(website.additionalAnnualInquiries)} demandes et ${number.format(website.additionalAnnualCustomers)} nouveaux clients possibles par année` : `${number.format(website.additionalAnnualInquiries)} potential additional inquiries and ${number.format(website.additionalAnnualCustomers)} customers per year`, href: `/${locale}/contact?intent=website&goal=${encodeURIComponent("Website opportunity estimate: " + money.format(website.potentialAnnualValue))}` },
    { key: "event", icon: Users, title: fr ? "Valeur du suivi après événement" : "Event follow-up opportunity", intro: fr ? "Estimez la valeur possible d’un suivi plus complet après un événement." : "Estimate the potential value of more complete event follow-up.", inputs: <><NumberField label={field.leads} value={leads} onChange={setLeads} /><NumberField label={field.currentFollow} value={currentFollow} onChange={setCurrentFollow} suffix="%" /><NumberField label={field.targetFollow} value={targetFollow} onChange={setTargetFollow} suffix="%" /><NumberField label={field.close} value={eventClose} onChange={setEventClose} suffix="%" /><NumberField label={field.customer} value={eventValue} onChange={setEventValue} suffix="$" /></>, result: money.format(event.potentialValue), detail: fr ? `${number.format(event.additionalFollowUps)} suivis et ${number.format(event.potentialCustomers)} clients possibles` : `${number.format(event.additionalFollowUps)} additional follow-ups and ${number.format(event.potentialCustomers)} potential customers`, href: `/${locale}/contact?intent=digital-events&goal=${encodeURIComponent("Event follow-up estimate: " + money.format(event.potentialValue))}` },
  ] as const;

  return <div className="space-y-7">
    <div className="grid gap-6 xl:grid-cols-3">{cards.map((card) => <article key={card.key} className="flex flex-col rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><card.icon className="h-7 w-7 text-primary-dark" aria-hidden /><h2 className="mt-4 text-2xl font-serif font-bold text-slate-950">{card.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{card.intro}</p><div className="mt-6 grid gap-4">{card.inputs}</div><div className="mt-6 rounded-xl bg-primary/[0.06] p-5"><p className="text-xs font-bold uppercase tracking-wide text-primary-dark">{fr ? "Valeur annuelle indicative" : "Indicative annual value"}</p><p className="mt-1 text-3xl font-bold text-slate-950">{card.result}</p><p className="mt-2 text-xs leading-5 text-slate-600">{card.detail}</p></div><a href={card.href} onClick={() => trackAnalyticsEvent("business_value_calculated", { calculator: card.key })} className="mt-5 inline-flex min-h-[48px] items-center justify-center rounded-lg bg-primary px-5 py-3 font-semibold text-white hover:bg-primary-dark">{fr ? "Faire valider cette possibilité" : "Validate this opportunity"}<ArrowRight className="ml-2 h-4 w-4" aria-hidden /></a></article>)}</div>
    <aside className="rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><div className="flex gap-3"><Calculator className="mt-1 h-5 w-5 shrink-0" aria-hidden /><p>{fr ? "Ces résultats sont des estimations de planification, pas des prévisions ni des garanties. Ils ne tiennent pas compte des coûts de mise en œuvre, de l’adoption, des contraintes techniques, des taxes ou d’autres facteurs. ROALLA valide les données et la faisabilité avant de recommander un investissement." : "These results are planning estimates, not forecasts or guarantees. They do not include implementation costs, adoption, technical constraints, taxes, or other factors. ROALLA validates the inputs and feasibility before recommending an investment."}</p></div></aside>
  </div>;
}
