"use client";

import { useEffect, useState } from "react";
import { ArrowRight, Plus, Trash2 } from "lucide-react";
import { Link } from "@/i18n/navigation";

type Item = { id: number; priority: string; owner: string; measure: string; status: string; review: string };
const blank = (): Item => ({ id: Date.now(), priority: "", owner: "", measure: "", status: "Not started", review: "" });
const inputClass = "w-full rounded-md border border-slate-300 bg-white px-2.5 py-2 text-sm text-slate-800";

export default function ExecutionPartnerDashboard({ locale }: { locale: string }) {
  const fr = locale === "fr";
  const [items, setItems] = useState<Item[]>([blank()]);
  const [ready, setReady] = useState(false);
  useEffect(() => { try { const stored = JSON.parse(localStorage.getItem("roalla-execution-dashboard") || "null"); if (Array.isArray(stored) && stored.length) setItems(stored); } catch {} setReady(true); }, []);
  useEffect(() => { if (ready) localStorage.setItem("roalla-execution-dashboard", JSON.stringify(items)); }, [items, ready]);
  const change = (id: number, key: keyof Item, value: string) => setItems((current) => current.map((item) => item.id === id ? { ...item, [key]: value } : item));
  return <div>
    <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold uppercase text-slate-500">{fr ? "Priorités actives" : "Active priorities"}</p><p className="mt-1 text-3xl font-bold text-slate-950">{items.filter((item) => item.status !== "Complete").length}</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold uppercase text-slate-500">{fr ? "Terminées" : "Complete"}</p><p className="mt-1 text-3xl font-bold text-slate-950">{items.filter((item) => item.status === "Complete").length}</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold uppercase text-slate-500">{fr ? "Prochaine habitude" : "Recommended rhythm"}</p><p className="mt-1 text-base font-bold text-slate-950">{fr ? "Examen mensuel" : "Monthly review"}</p></div></div>
    <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="text-xl font-serif font-bold text-slate-950">{fr ? "Tableau d'exécution" : "Execution board"}</h2><p className="mt-1 text-sm text-slate-600">{fr ? "Donnez à chaque priorité un responsable, une mesure et une date d'examen." : "Give every priority an owner, a measure, and a review date."}</p></div><div className="space-y-4 p-5">{items.map((item) => <div key={item.id} className="grid gap-3 rounded-xl bg-slate-50 p-4 lg:grid-cols-[1.5fr_1fr_1.2fr_1fr_1fr_auto]">
      <input aria-label={fr ? "Priorité" : "Priority"} placeholder={fr ? "Priorité" : "Priority"} value={item.priority} onChange={(e) => change(item.id, "priority", e.target.value)} className={inputClass}/><input aria-label={fr ? "Responsable" : "Owner"} placeholder={fr ? "Responsable" : "Owner"} value={item.owner} onChange={(e) => change(item.id, "owner", e.target.value)} className={inputClass}/><input aria-label={fr ? "Mesure" : "Measure"} placeholder={fr ? "Mesure du progrès" : "Progress measure"} value={item.measure} onChange={(e) => change(item.id, "measure", e.target.value)} className={inputClass}/><select aria-label={fr ? "État" : "Status"} value={item.status} onChange={(e) => change(item.id, "status", e.target.value)} className={inputClass}><option value="Not started">{fr ? "Non commencé" : "Not started"}</option><option value="In progress">{fr ? "En cours" : "In progress"}</option><option value="At risk">{fr ? "À risque" : "At risk"}</option><option value="Complete">{fr ? "Terminé" : "Complete"}</option></select><input aria-label={fr ? "Date d'examen" : "Review date"} type="date" value={item.review} onChange={(e) => change(item.id, "review", e.target.value)} className={inputClass}/><button type="button" aria-label={fr ? "Supprimer" : "Remove"} onClick={() => setItems((current) => current.filter((entry) => entry.id !== item.id))} className="rounded-md p-2 text-slate-500 hover:bg-red-50 hover:text-red-700"><Trash2 className="h-4 w-4" /></button>
    </div>)}</div><div className="border-t border-slate-200 p-5"><button type="button" onClick={() => setItems((current) => [...current, blank()])} className="inline-flex items-center text-sm font-semibold text-primary-dark"><Plus className="mr-2 h-4 w-4" />{fr ? "Ajouter une priorité" : "Add a priority"}</button></div></section>
    <div className="mt-6 rounded-xl border border-primary/20 bg-primary/[.05] p-5 text-sm leading-6 text-slate-700"><p><strong>{fr ? "Aperçu privé :" : "Private preview:"}</strong> {fr ? "Vos entrées restent dans ce navigateur. Il ne s'agit pas d'un compte client actif et ROALLA ne peut pas voir, récupérer ou sauvegarder ces données." : "Your entries stay in this browser. This is not an active client account, and ROALLA cannot view, recover, or back up this information."}</p><Link href={{ pathname: "/contact", query: { intent: "consulting", focus: "execution-partner" } }} className="mt-3 inline-flex items-center font-semibold text-primary-dark hover:underline">{fr ? "Discuter d'un accompagnement d'exécution" : "Discuss execution support"}<ArrowRight className="ml-2 h-4 w-4" /></Link></div>
  </div>;
}
